### ISSUE TITLE
[Feature Request]: Add problems on String 

### ISSUE THREAD

**Issue by MuraliDharan7** [CodeHarborHub/codeharborhub.github.io#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I have over 15 problems in Strings, which is divided as easy and medium difficulty problems. I want to add them in problems page.

### Use Case

Helps users to quickly go through particular topic and learn all the things.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@MuraliDharan7 Please complete your task otherwise I will close it.
