### ISSUE TITLE
I want to add leetcode solutions for problems 36(medium) and 37(hard).

### ISSUE THREAD

**Issue by AbhishiktaRay03** [CodeHarborHub/codeharborhub.github.io#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

How many minimum questions' solutions do I need to provide for getting assigned a task?

### Suggested Change

I will provide varied approaches and solutions in languages to solve this issue which I myself did in leetcode.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AbhishiktaRay03** [comment]
@Ajay-Dhangar  I had raised this issue seeing that the solutions of these problems were not visible in the website, however, in GitHub folder directory the .md file is there and I can see someone has the documentation written. What should I do now?

**Comment by Ajay-Dhangar** [comment]
@AbhishiktaRay03 , I apologize for not providing feedback some time ago moment as I am occupied with my tasks. If you would like to write your code for our documentation, please work in the dsa-solution directory.

**Comment by Ajay-Dhangar** [comment]
@AbhishiktaRay03 Please complete your task otherwise I will close it.

**Comment by AbhishiktaRay03** [comment]
I was stuck with my exams. I'll complete it by tonight.
