### ISSUE TITLE
[Feature Request]: Add Leetcode Solution for 345 and 345 problems

### ISSUE THREAD

**Issue by Ashu0216** [CodeHarborHub/codeharborhub.github.io#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add solutions for the following problems:
[**344. Reverse String**] (https://leetcode.com/problems/reverse-string)
[**345. Reverse Vowels of a String**] (https://leetcode.com/problems/reverse-vowels-of-a-string)

### Use Case

Add solution in leetcode solution section

### Benefits

Provide additional solutions to user

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ashu0216** [comment]
Hi @Ajay-Dhangar , Can you please assign me this issue

**Comment by Ajay-Dhangar** [comment]
@Ashu0216 Please complete your task otherwise I will close it.

**Comment by Ashu0216** [comment]
Hi @Ajay-Dhangar , apologies for the delay. Will get the issue completed before Monday

**Comment by UtkarshBirla28** [comment]
@Ashu0216  assign me this issue i will try to resolve it  today only

**Comment by Ashu0216** [comment]
@UtkarshBirla28 I have started working on it...will resolve today

**Comment by UtkarshBirla28** [comment]
@Ashu0216 Okayyyy good good.

**Comment by Ajay-Dhangar** [comment]
> @UtkarshBirla28 I have started working on it...will resolve today

Okay complete this very soon

**Comment by Ajay-Dhangar** [comment]
@Ashu0216 Please complete your task otherwise I will close it.

**Comment by UtkarshBirla28** [comment]
@Ajay-Dhangar Assign it to me i will resolve it ASAP
