### ISSUE TITLE
[Feature Request]: Add git docs 

### ISSUE THREAD

**Issue by root-0101** [CodeHarborHub/codeharborhub.github.io#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As git is most demanding and import software, we need to add git docs 

### Use Case

It helps user to learn the git from basic to advance

### Benefits

The git docs help the people to know about it's command and how to use it efficiently 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@root-0101 Please complete your task otherwise I will close it.
