### ISSUE TITLE
[Feature Request]: Adding Computer Networking docs

### ISSUE THREAD

**Issue by root-0101** [CodeHarborHub/codeharborhub.github.io#1050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Computer networking is the building blocks of a person who starts in IT so, having an amazing docs on networking helps them to gin this skill

### Use Case

This docs help the people to know how data transfer from one point to another and know how actually internet works

### Benefits

It help them to make a person foundation strong and help them to grab a good understanding of the networking and improve their skills

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@root-0101 Please complete your task otherwise I will close it.
