### ISSUE TITLE
[Bug]: Button is not visible in dark 

### ISSUE THREAD

**Issue by root-0101** [CodeHarborHub/codeharborhub.github.io#1052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The buttons when scrolled to the footer section, they are not clearly visible

### Expected behavior

the buttons must be visible clearly

### Add ScreenShots

![Screenshot 2024-06-12 003935](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/142779809/59ff8b8e-f054-404b-b423-007a690e8342)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@root-0101 https://codeharborhub.github.io/ this is our latest url for all latest code so, checkout and I want to close this issue because I can't need this and I already put all functionality and styles for response, and dark/light every form

**Comment by Ajay-Dhangar** [comment]
@root-0101 I want to say to you. you need to use our latest main branch
