### ISSUE TITLE
[Feature Request]: Wants To Add Sol of LC Problem 875. Koko Eating Bananas

### ISSUE THREAD

**Issue by aryan-1309** [CodeHarborHub/codeharborhub.github.io#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

875. Koko Eating Bananas is a famous problem of Binary search and i want to add it's sol. pls assign this to me. Thanks...

### Use Case

Repetative asking problem in Most of interviews. it'll be helpful for others.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@aryan-1309  please complete your task otherwise i will close it
