### ISSUE TITLE
[Feature Request]: Improve the UI of Navbar

### ISSUE THREAD

**Issue by PuR-vI** [CodeHarborHub/codeharborhub.github.io#1063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I'd like to enhace the UI of the navbar to make it look more dynamic and align it with the page theme.

### Use Case

This will make the system look even and organised and make the UI engaging

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PuR-vI** [comment]
Can you add level and GSSOC labels please?

**Comment by Ajay-Dhangar** [comment]
@PuR-vI could you please explain which specific aspect you want to change? Our navbar is fully functional, responsive, and designed professionally. Providing more details will help me understand better and assist you more effectively.

**Comment by PuR-vI** [comment]
Sure. A hover effect can be added to the links or a animated underline would make it look  more appealing. Also the search bar could be enhanced to look better. id also change the entire color of the navbar as to clearly separate it from the rest of the content. The logo could also be animated
