### ISSUE TITLE
[Feature Request]: Align the resources into a single div.

### ISSUE THREAD

**Issue by PuR-vI** [CodeHarborHub/codeharborhub.github.io#1064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/97090750/bf21ba51-1b2b-44c0-b63a-72262b5def39)
This bar at the top looks out of place. I'd like to change that and align all of it into a single div so that section looks uniform.

### Use Case

This will imporve the UI and give a uniform and neat look to the page 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PuR-vI** [comment]
Please add the labels. Thanks!

**Comment by Ajay-Dhangar** [comment]
@PuR-vI it's already okay, and if you want to work on it then can you define problem and how to you solve because I can't want to change its. It is already, good.

**Comment by Ajay-Dhangar** [comment]
@PuR-vI I want to need FAQ section for home page you can work on it

**Comment by PuR-vI** [comment]
Okay sure should I raise a new issue?

**Comment by Ajay-Dhangar** [comment]
open new issue and work on it. if you need any help then ask me, I will help you.
