### ISSUE TITLE
[Feature Request]: Adding a FAQ page 

### ISSUE THREAD

**Issue by PuR-vI** [CodeHarborHub/codeharborhub.github.io#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I'd like to add an FAQ page for the website 

### Use Case

This will help the user to navigate the website properly 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PuR-vI** [comment]
Thanks ! I'll post an update in a few days.

**Comment by PuR-vI** [comment]
Hey if there are any specific FAQ youd like me to add please let me know

**Comment by Ajay-Dhangar** [comment]
@PuR-vI Please complete your task otherwise I will close it.
