### ISSUE TITLE
Adding solutions to gfg basic problems (0001 to 0100)

### ISSUE THREAD

**Issue by Ishita-Jena** [CodeHarborHub/codeharborhub.github.io#1085]
I want to add solutions to all the problems in 0001-0100.md in the basic folder of gfg problems. Each problem will have its md file and be solved using python, java, c++ and c.

**Comment by Ajay-Dhangar** [comment]
@Ishita-Jena Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support

**Comment by Ishita-Jena** [comment]
Please give me a bit more time. I'll raise the pr by tomorrow.
