### ISSUE TITLE
[Feature Request]:Add a BMI calculator to all site  section 

### ISSUE THREAD

**Issue by parikhitritgithub** [CodeHarborHub/codeharborhub.github.io#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a BMI calculator to all site  section 

### Use Case

Anyone can check the BMI of their body

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@parikhitritgithub Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support

**Comment by parikhitritgithub** [comment]
ok i will do it by tomorrow
