### ISSUE TITLE
[Feature Request]: Adding  preorder, postorder, and inorder traversal techniques to the Tree section

### ISSUE THREAD

**Issue by parikhitritgithub** [CodeHarborHub/codeharborhub.github.io#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding  preorder, postorder, and inorder traversal techniques to the Tree section

### Use Case

Use for enhancing knowledge and  learning

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@parikhitritgithub Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support

**Comment by parikhitritgithub** [comment]
i will do it by tomorrow

**Comment by parikhitritgithub** [comment]
please don't close this  issue i will merge it by 1 pm
