### ISSUE TITLE
Add Advanced Concepts In Python

### ISSUE THREAD

**Issue by VaishnaviMankala19** [CodeHarborHub/codeharborhub.github.io#1097]
I want to add a folder as advanced concepts in python and this folder consists about filter function in python , reduce function , map function

**Comment by VaishnaviMankala19** [comment]
@Ajay-Dhangar  I propose creating a separate folder titled "Advanced Concepts" that includes detailed descriptions, syntax, examples, applications, pros, and cons for each advanced Python function (filter, map, reduce). This addition will provide comprehensive insights and enhance the documentation's utility for advanced users. Can I get level3 for this

**Comment by Ajay-Dhangar** [comment]
@VaishnaviMankala19 Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support

**Comment by VaishnaviMankala19** [comment]
Hey , @Ajay-Dhangar I will complete it by today
