### ISSUE TITLE
[Feature Request]: Sudoku Solver

### ISSUE THREAD

**Issue by Damini2004** [CodeHarborHub/codeharborhub.github.io#1121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

providing solution to leetcode problem - 37

### Use Case

I would add proper solutions for the problem in three different programing languages i.e C++,Java,and Python with proper documentation

### Benefits

Users can access solution to problem 473

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Damini2004 Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support
