### ISSUE TITLE
[Feature Request]: Add Hover effects on Scrollbar So user feel that he/she holding scrollbar.

### ISSUE THREAD

**Issue by zalabhavy** [CodeHarborHub/codeharborhub.github.io#1123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to give hover effects to Scrollbar so user can feel that scrolling effects.

### Use Case

Better experience.

### Benefits

Good feeling in website scrolling when scroll by holding scrollbar.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Rahban1** [comment]
can  I work on this ?
