### ISSUE TITLE
Introduction To Java

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub.github.io#113]
Covered three topics [code](https://github.com/CodeHarborHub/codeharborhub/tree/main/docs/java/introduction-to-java) and [preview](https://www.codeharborhub.live/docs/category/introduction-to-java). 

- [ ] What is Java?
- [ ] Why Learn Java?
- [ ] Setup Java Development Environment

**Resources for Guidance**

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- https://www.codeharborhub.live/community/features
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Our Site Features**

https://www.codeharborhub.live/community/features

**Comment by Tirth-chokshi** [comment]
Hello @Ajay-Dhangar i can complete this ! please assign me this issue under GSSOC'24

**Comment by geesadbandara** [comment]
I can also go with this issue, can you please add me too !
