### ISSUE TITLE
[Feature Request]: preloader

### ISSUE THREAD

**Issue by Jagpreet153** [CodeHarborHub/codeharborhub.github.io#1135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to adda a preloader to increase the user interest . It would be rendered until the page is being loaded

### Use Case

It would be completely responsive and matching the theme of this project

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@
