### ISSUE TITLE
Add Icons to Navbar

### ISSUE THREAD

**Issue by sailaja-adapa** [CodeHarborHub/codeharborhub.github.io#1141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add icons to the Navbar Items to make the website look Attractive

Can you please assign me this issue under gssoc'24 @Ajay-Dhangar 

### Use Case

It will Enhance User Experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Tanishka023** [comment]
Hey @hardiksharma02   Please assign this to me under GSSoC'24, I can fix this easily as I have already worked on this. I agree to follow the code of conduct of GSSoC'24.

Regards,
Tanishka Bhalla

**Comment by sailaja-adapa** [comment]
@Ajay-Dhangar Please assign this issue to @Tanishka023 may be i am not able to complete this now Thank you so much for your concern @Ajay-Dhangar
