### ISSUE TITLE
Add a Preloader 

### ISSUE THREAD

**Issue by 1754riya** [CodeHarborHub/codeharborhub.github.io#1154]
Adding a preloader to your website can help improve its smooth operation.
@CodeHarborHub, Please assign me this issue.
I'm Gssoc'24 contributor.

**Comment by Ajay-Dhangar** [comment]
> Adding a preloader to your website can help improve its smooth operation. @CodeHarborHub, Please assign me this issue. I'm Gssoc'24 contributor.

can you share more details for better understanding for me of your issue?

**Comment by 1754riya** [comment]
### Feature Description
I would like to add a preloader to increase user interest. It would be displayed until the page is fully loaded.
### Use Case
It would be completely responsive and match the theme of this project.

### Priority
High

### Record
 I have read the Contributing Guidelines
 I'm a GSSOC'24 contributor
 I have starred the repository.
@Ajay-Dhangar, Please assign me this issue.

**Comment by Ajay-Dhangar** [comment]
But this issue already created https://github.com/CodeHarborHub/codeharborhub.github.io/issues/1135. So, you need create different.
