### ISSUE TITLE
Feature : A go-to-top arrow icon on footer , clicking on it will direct to Navbar.

### ISSUE THREAD

**Issue by Suvam3456** [CodeHarborHub/codeharborhub.github.io#120]
Hello Project Admin , I can add a go-to-top icon on the footer of your website and by clicking on that, user will be directed to the top at Navbar.

Example image of any random website :
![329804903-bf27e71f-72f0-45ac-a44b-95aa00418dcd](https://github.com/CodeHarborHub/codeharborhub/assets/99579881/7fac1c09-2943-4f2c-a702-401409435e3a)

Please Assign me this issue under label of GSSOC'24 and also add level label so that i can get points for my work

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar i'd love to work on this!
