### ISSUE TITLE
[Bug]: Quiz Page Error

### ISSUE THREAD

**Issue by CoderGirl2844** [CodeHarborHub/codeharborhub.github.io#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot 2024-06-14 130425](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/155231566/40ae229f-75f6-45f7-87eb-bc82e3a00db1)
After selecting the quiz option in nav bar it throws an error

### Expected behavior

Add a quiz page regarding the DSA topics which would be helpful for the users to test their DSA theory.

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@CoderGirl2844 Quiz app not part of our site it is other site so, can't work on it and you can created new issue
