### ISSUE TITLE
[Feature Request]:  Add Dynamic Programming Documentation 

### ISSUE THREAD

**Issue by aasthakourav20** [CodeHarborHub/codeharborhub.github.io#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey I would Like to add Dynamic Programming section in the DSA Solutions 

### Use Case

It will be useful for the users while solving various Problems

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@aasthakourav20 Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support
