### ISSUE TITLE
Leetcode solution to Number of changing keys

### ISSUE THREAD

**Issue by tanyagupta01** [CodeHarborHub/codeharborhub.github.io#1460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

You are given a 0-indexed string s typed by a user. Changing a key is defined as using a key different from the last used key. For example, s = "ab" has a change of a key while s = "bBBb" does not have any.

Return the number of times the user had to change the key.

Note: Modifiers like shift or caps lock won't be counted in changing the key that is if a user typed the letter 'a' and then the letter 'A' then it will not be considered as a changing of key.

### Suggested Change

i will add a detailed solution to the problem as mentioned above.

### Urgency

High

### Acknowledgements

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository
- [X] I have read and followed the Contribution Guidelines
- [X] I have followed the code style guidelines of this project
- [X] I have checked for any existing open issues that my pull request may address
- [X] I have ensured that my changes do not break any existing functionality
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently
- [X] I have read the resources for guidance listed below
- [X] I have not used AI-generated content (e.g., ChatGPT, other AI tools)
- [X] I have not used content from existing sites (e.g., text, images)
- [X] I have followed all security rules and only shared trusted resources

**Comment by Ajay-Dhangar** [comment]
@tanyagupta01 Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support

**Comment by tanyagupta01** [comment]
@Ajay-Dhangar okay, I will complete it soon

**Comment by Ajay-Dhangar** [comment]
@tanyagupta01 Please complete your task.
