### ISSUE TITLE
[Feature Request]: To add lc-198 solution.

### ISSUE THREAD

**Issue by maradadivyasree020** [CodeHarborHub/codeharborhub.github.io#1463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add leetcode question 198.

### Use Case

I want to add leetcode question 198.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@maradadivyasree020 you can anly open 4 issue
