### ISSUE TITLE
[Bug]: Favicon missing in Quiz App

### ISSUE THREAD

**Issue by zalabhavy** [CodeHarborHub/codeharborhub.github.io#1480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no favicon in quiz app

### Expected behavior

i will add favicon to this page.

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/126322584/380b106f-fe1c-46c9-a67f-66ada291d4ba)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@Ajay-Dhangar Please assign me !

**Comment by zalabhavy** [comment]
Hey @Ajay-Dhangar Can you please help me where is quiz file and where is favicon image is stored ?
I can't able to find that.

**Comment by Ajay-Dhangar** [comment]
@zalabhavy Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support
