### ISSUE TITLE
[Feature Request]: Add new Blog Getting started with PostgreSQL

### ISSUE THREAD

**Issue by Nayanika1402** [CodeHarborHub/codeharborhub.github.io#1531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The topics that this blog will contain:
1)Introduction to PostgreSQL
2)History
3)Installing PostgreSQL
4)Basic PostgreSQL Configuration
5)Connecting to PostgreSQL
6)Basic SQL Commands in PostgreSQL
7)Advanced SQL Features
8)Security and User Management
9)Extensions and Customizations

### Use Case

This blog will contain useful information about PostgreSQL which will be beneficial for others.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Nayanika1402 Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support

**Comment by Nayanika1402** [comment]
@Ajay-Dhangar I will submit the pr within tomorrow.No issues.
