### ISSUE TITLE
[Feature Request]:  Quiz section in tailwind

### ISSUE THREAD

**Issue by mukilan2815** [CodeHarborHub/codeharborhub.github.io#1548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As many students are lagging in mcqs in placements. Quiz section will be very much helpful for them. 

### Use Case

It will help students to practice the mcqs before placements or interviews.

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/71129858/2c91a774-61dc-4197-9a05-e694ffbfc1e9)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by mukilan2815** [comment]
Can you label level 2 atleast coz its time consuming task for adding more questions , and validating answers. @Ajay-Dhangar

**Comment by Ajay-Dhangar** [comment]
@mukilan2815 Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support

**Comment by mukilan2815** [comment]
I will complete within 2 days

**Comment by Ajay-Dhangar** [comment]
> I will complete within 2 days

Ok

**Comment by Ajay-Dhangar** [comment]
@mukilan2815 Please complete your task.

**Comment by Khushi-Pushkar** [comment]
@Ajay-Dhangar can u assign this issue to me

**Comment by Khushi-Pushkar** [comment]
@Ajay-Dhangar can u pls assign this issue to me

**Comment by Khushi-Pushkar** [comment]
@Ajay-Dhangar pls assign this issue to me

**Comment by Khushi-Pushkar** [comment]
@Ajay-Dhangar pls assign this issue to me

**Comment by Ajay-Dhangar** [comment]
@Khushi-Pushkar now work on it

**Comment by Amruta7203** [comment]
@Ajay-Dhangar Pls assign this task to me..

**Comment by Khushi-Pushkar** [comment]
Hey @Amruta7203 . I am currently working on that task. While it may seem easy, it is actually quite challenging. Therefore, I will need some more time to complete it. In the meantime, you may address other issues or create new issues related to the quiz section in different languages.
