### ISSUE TITLE
[Feature Request]: Addition of MARKDOWN language in tutorials

### ISSUE THREAD

**Issue by DhayanandhS** [CodeHarborHub/codeharborhub.github.io#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Introduce a comprehensive Markdown tutorial section to the [https://github.com/CodeHarborHub](https://codeharborhub.github.io/docs/) platform. This feature will provide users with detailed instructions and examples on how to use Markdown for documentation and content creation. The new section will be accessible from the main navigation menu under "Tutorials."

### Use Case

- Provide users with a thorough understanding of Markdown syntax and usage.
- Enhance the educational resources available on CodeHarborHub.
- Improve user engagement by offering valuable content creation tutorials.

### Benefits

- Educates users on effectively using Markdown for their projects.
- Enhances the value of CodeHarborHub as an educational resource.
- Encourages user interaction and engagement with the platform.
- Supports users in creating better documentation and content.
By adding a Markdown tutorial to CodeHarborHub, we can provide a valuable resource that will help users improve their documentation skills and overall project quality.

### Add ScreenShots

![Screenshot 2024-06-18 122820](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/112493275/09f1b146-eae8-496a-98e3-f053b54c1ad2)

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/112493275/cd587e3c-0482-48c0-8497-5e435157d632)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@DhayanandhS Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support

**Comment by DhayanandhS** [comment]
Hi @Ajay-Dhangar , I'm having semester exams right this month. You can assign it to some other contributor or close it. And I'm really sorry for not letting you know. I thought I could start working on it but I guess I could not complete it. If I did anything wrong I'm sorry again!
