### ISSUE TITLE
[Feature Request]: Adding leetcode-3110 Score of a String

### ISSUE THREAD

**Issue by SadafKausar2025** [CodeHarborHub/codeharborhub.github.io#1574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

.

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@SadafKausar2025 Please complete your task otherwise I will close it. and if you have any queries then ask me on our live chat for support: https://codeharborhub.github.io/community/supports#-how-to-get-support

**Comment by SadafKausar2025** [comment]
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1665
hello @Ajay-Dhangar 
you have already merge this PR of score of string.

**Comment by SadafKausar2025** [comment]
I have already done with this issue
