### ISSUE TITLE
[Bug]: Fix Alignment of "Problem" and "Solution" Text in the Header

### ISSUE THREAD

**Issue by Saksham2k3s** [CodeHarborHub/codeharborhub.github.io#1583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The alignment of the "Problem" and "Solution" text in the header is not perfect. The text appears misaligned and affects the overall visual appeal of the header.

### Expected behavior

The "Problem" and "Solution" text in the header should be perfectly aligned to ensure a clean and professional look.

### Add ScreenShots

![modal ](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/129402285/7b519269-8327-4fc9-b36c-7f017e53ba86)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Saksham2k3s May be you can use icons for this for best way
