### ISSUE TITLE
[Documentation Update]: Want to add a Blog about Cryptography and it's use in Cyber Security

### ISSUE THREAD

**Issue by Pujan-sarkar** [CodeHarborHub/codeharborhub.github.io#1602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I will add a documentation about cryptography and it's use / relation with cyber security. And how it will help in Cyber security world.

### Suggested Change

This documentation will help everyone in growth of Cyber Security and cryptography.

### Urgency

Medium

### Acknowledgements

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository
- [X] I have read and followed the Contribution Guidelines
- [X] I have followed the code style guidelines of this project
- [X] I have checked for any existing open issues that my pull request may address
- [X] I have ensured that my changes do not break any existing functionality
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently
- [X] I have read the resources for guidance listed below
- [X] I have not used AI-generated content (e.g., ChatGPT, other AI tools)
- [X] I have not used content from existing sites (e.g., text, images)
- [X] I have followed all security rules and only shared trusted resources

**Comment by Ajay-Dhangar** [comment]
@Pujan-sarkar Please complete your task otherwise I will close it.

**Comment by Pujan-sarkar** [comment]
@Ajay-Dhangar sir give me some time I will complete this within today
