### ISSUE TITLE
[Feature Request]: Leetcode Problem 741 - (Cherry Pickup - Hard) 

### ISSUE THREAD

**Issue by shreyash3087** [CodeHarborHub/codeharborhub.github.io#1615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Provide Solution To Leetcode Problem 741 - (Cherry Pickup)

### Use Case

I would add proper solutions for the problem in three different programing languages i.e C++,Java,and Python with proper documentation

### Benefits

Users can access solution to problem 741

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Dear @shreyash3087 ,

Thank you for your valuable contributions to our open-source project. We appreciate your hard work and dedication. However, we kindly request that you limit the number of issues and PRs you create during the GSSoC'24 period. Our goal is to provide opportunities for all contributors participating in GSSoC'24 to achieve their milestones and earn rewards by working on simpler tasks within our project.

After GSSoC'24, we would be delighted to have you work with us full-time, and we look forward to your continued contributions. If you have any questions or need assistance, please reach out to @sanjay-kv , who will be happy to help.

Thank you for your understanding and cooperation.

Best regards,  
@Ajay-Dhangar

**Comment by Ajay-Dhangar** [comment]
I suggest you create only 2 issues per day and focus on improving content quality. I have many tasks related to assigning issues and maintaining contributors, which limits my ability to concentrate on content quality and improvements based on my reviews. Please understand my situation.

**Comment by Ajay-Dhangar** [comment]
And one more best our features I want to share with you for improve content Quality based on video content from YoutTube (for DSA solution)

Example:

```js
<LiteYouTubeEmbed
    id="lI3RBnK8V6Y"
    params="autoplay=1&autohide=1&showinfo=0&rel=0"
    title="CodeHarborHub Website Introduction | CodeHarborHub Website Overview | CodeHarborHub Website Features"
    poster="maxresdefault"
    webp />
```

**Comment by shreyash3087** [comment]
@Ajay-Dhangar 

Thank you for your feedback and guidance. I understand the need to manage the number of issues and PRs during the GSSoC'24 period to ensure all contributors have a fair chance to participate and reach their milestones. I appreciate the opportunity to continue contributing and will obey to the suggested limit of creating only 2 issues per day. I will also focus on improving the quality of my contributions.
The LiteYouTubeEmbed feature you mentioned sounds like a great tool to enhance content quality. I'll certainly explore it and integrate video content to provide better understanding and value.
