### ISSUE TITLE
[Feature Request]: Give Hover Scale to Get Start and Course button 

### ISSUE THREAD

**Issue by zalabhavy** [CodeHarborHub/codeharborhub.github.io#1624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to give scale less than 1 so when user hover he/she feel that button is push down when he/she hover on that.

### Use Case

It gives better experience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@zalabhavy but in the professional way this is not good because our site is not a just like project we want to make it valuable and best site for learners

**Comment by Ajay-Dhangar** [comment]
So, i want to close It
