### ISSUE TITLE
[Feature Request]: Add Course Progress Tracking for Users

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [CodeHarborHub/codeharborhub.github.io#1633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Users currently do not have a way to track their progress in the various courses offered on CodeHarborHub. Implementing a course progress tracking feature will enhance the user experience by allowing users to see which lessons they have completed and what remains, thus making the learning process more structured and motivating.

### Use Case

Imagine a user enrolled in a web development course. As they complete each lesson, a progress bar or checklist updates to show their progress. This visual representation keeps them motivated and organized, ensuring they can easily pick up where they left off if they return after a break

### Benefits

Personalization: Users can track their own learning journey and revisit incomplete lessons.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@AKSHITHA-CHILUKA Please complete your task otherwise I will close it.

**Comment by AKSHITHA-CHILUKA** [comment]
I am working on it 
I will update soon
