### ISSUE TITLE
[PHP Docs]: Add PHP Docs  21 to 26

### ISSUE THREAD

**Issue by Vipullakum007** [CodeHarborHub/codeharborhub.github.io#1646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add Following docs of PHP.

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/97159f61-cd53-4bc5-8538-4266842e5c6f)

### Use Case

User can know more about PHP.

### Benefits

User can know more about PHP.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Vipullakum007 Please complete your task otherwise I will close it.

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , don't close it i will complete till tomorrow.
