### ISSUE TITLE
[PHP Docs]: Add PHP Docs 33 to 37 UNDER new Folder PHP Operators

### ISSUE THREAD

**Issue by Vipullakum007** [CodeHarborHub/codeharborhub.github.io#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add PHP Docs 27 to 32 UNDER new Folder PHP Operators

![Screenshot 2024-06-19 173805](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/07566c11-4553-49dd-afee-605ea7d6df8d)

### Use Case

User can know more about PHP Language

### Benefits

User can know more about PHP Language

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Vipullakum007 Please complete your task otherwise I will close it.

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , don't close it i will complete till tomorrow.
but please reply my question in mine previous PR. https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1625#issuecomment-2184379556
