### ISSUE TITLE
[Feature Request]: Add Problems on Sliding Window

### ISSUE THREAD

**Issue by ishap11** [CodeHarborHub/codeharborhub.github.io#1696]
### Is there an existing issue for this?
- [X] I have searched the existing issues

### Feature Description
Hello, this is Isha Prajapati, I hope you're doing well.
I have over 13 problems in the Sliding Window category, divided into easy and medium difficulty levels. I would like to contribute by adding these problems to the problems page.

As a participant of GSSoC'24, I am eager to enhance our website’s functionality and user experience. Please assign this task to me.
Thank you!

### Use Case
Adding a specific set of problems focused on the Sliding Window technique will help users quickly learn and practice this topic, improving their skills and understanding.

### Priority
High

### Record
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@ishap11 Please complete your task otherwise I will close it.
