### ISSUE TITLE
Leetcode]: i want to add Leetcode Solution for the Problem Number 2790 "Maximum Number of Groups With Increasing Length" (Hard)

### ISSUE THREAD

**Issue by vivekvardhan2810** [CodeHarborHub/codeharborhub.github.io#1979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to Add the solution of Leetcode problem 2790. Maximum Number of Groups With Increasing Length

### Use Case

it will help the users to get the solution for the Leetcode problem 2790

### Benefits

The Users Can Understand the problem and they may try for alternate solution if they can't get it

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sjain1909** [comment]
@Ajay-Dhangar Please assign me this issue.

**Comment by vivekvardhan2810** [comment]
@sjain1909, Brother it's already issued for me and I am working on it
