### ISSUE TITLE
[Feature Request]: Add gfg solution "missing-number-in-array1416"

### ISSUE THREAD

**Issue by arunimaChintu** [CodeHarborHub/codeharborhub.github.io#1998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This will provide solution to gfg "missing-number-in-array1416"

### Use Case

used to solve the problem gfg "missing-number-in-array1416"

### Benefits

provides solution to gfg problem "missing-number-in-array1416"

### Add ScreenShots

<img width="603" alt="Screenshot 2024-06-24 at 12 53 58 PM" src="https://github.com/CodeHarborHub/codeharborhub.github.io/assets/99474881/34117842-f892-4e21-87b4-743dd42d208a">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by arunimaChintu** [comment]
Please assign me this issue

**Comment by sjain1909** [comment]
Please assign me this issue
