### ISSUE TITLE
Add Social Media Icons to Footer

### ISSUE THREAD

**Issue by shreyyq** [CodeHarborHub/codeharborhub.github.io#2047]
I'd like to add social media icons (Twitter, GitHub, LinkedIn, etc) to the footer of the website. Please assign this task to me.

**Comment by Ajay-Dhangar** [comment]
@shreyyq We don't prefer using icons in the footer. Therefore, you can close this issue. However, if you would still like to work on it, we will review your work. If it proves to be useful, we will merge it; otherwise, we will close it.
