### ISSUE TITLE
Feature Request: Add more sections to TypeScript Section

### ISSUE THREAD

**Issue by priyavratamohan** [CodeHarborHub/codeharborhub.github.io#219]
* **Description:** In the TypeScript Section, I would like to add more sections like Getting Started, and sections related to different datatypes, functions and classes etc. in order to make it a more complete section.
* **Use Case:** This feature will be useful to everyone looking for a head-start into TypeScript.

Please assign me this Issue under the Label of **GSSoC '24** and add label **'level 1'/'level 2'/'level 3'** according to your discretion.
Thank you!

**Comment by Ajay-Dhangar** [comment]
@priyavratamohan can you complete your task otherwise I will close it.

**Comment by priyavratamohan** [comment]
@Ajay-Dhangar yes, I'll just take one more day
