### ISSUE TITLE
[Feature Request]: When anyone submit get in touch form after that clear form and show messsage message sent successfully.

### ISSUE THREAD

**Issue by zalabhavy** [CodeHarborHub/codeharborhub.github.io#2250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to make form functional by reset form after submit and show message that message sent successfully

### Use Case

For better user experience

### Benefits

User satisfaction after submit message

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/126322584/a26c33d9-3cbf-4fb2-b608-81f6a42a5b21)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Okay, but in this time we not need it so can you create new issues
