### ISSUE TITLE
Add Organization Section

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub.github.io#2277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We propose adding an **Organization** section to the home page of our project website. This section will highlight our various GitHub organizations and repositories dedicated to different aspects of web development. It will provide learners with direct access to our open-source projects, allowing them to collaborate, contribute, and enhance their skills.

### Use Case

- **Learners**: Users seeking to improve their skills in HTML, CSS, JavaScript, React.js, and Node.js can explore our repositories, contribute to projects, and gain practical experience.
- **Contributors**: Experienced developers can join our community, share their knowledge, and help guide new learners through their coding journey.
- **Organizations**: Promote our organizations as hubs for quality learning resources and community-driven development.

### Benefits

- **Increased Engagement**: Providing easy access to our repositories will encourage more learners to join our community and contribute to our projects.
- **Community Building**: Highlighting our organizations fosters a sense of community and collaboration among learners and contributors.
- **Skill Development**: By participating in our projects, users can develop their skills through real-world coding experiences and collaborative efforts.
- **Visibility**: Promoting our GitHub organizations on the home page increases visibility and attracts more developers to our projects.

### Organization Links

- [HTML-Mastery](https://github.com/HTML-Mastery)
- [CSS3-Mastery](https://github.com/CSS3-Mastery)
- [JavaScript-Mastery](https://github.com/JavaScript-Mastery)
- [React-js-Mastery](https://github.com/React-js-Mastery)
- [Node-Js-Mastery](https://github.com/Node-Js-Mastery)

### Additional Information

We have created several projects and repositories for learners, as well as open-source learning resources that users can easily collaborate on. These resources allow learners to contribute their work or tasks based on their learning skills, enhancing their development journey.

### Steps to Implement

1. **Design the Organization Section**: Create a visually appealing section on the home page that includes logos, descriptions, and links to our GitHub organizations.
2. **Develop the Section**: Implement the design using HTML, CSS, and JavaScript. Ensure the section is responsive and accessible.
3. **Link Repositories**: Add links to each of our GitHub organizations, providing a brief description of the focus and purpose of each.
4. **Deploy the Update**: Update the home page with the new section and ensure everything is functioning correctly.

We look forward to your feedback and contributions to make this feature a valuable addition to our project!

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/99037494/105f0957-e653-4d2f-8c6a-e4e903cf332e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
### Some Reference or Source useful for you to complete this task

- **Icons/logo:** https://icons8.com/icons
- **Structure:** image of icon/logo, title, description (like define our org or may be define tech)

   **For Example** 

   ![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/99037494/4c3f7d97-25b2-4195-ab95-f8aa792e585b)

**Comment by Hemu21** [comment]
@Ajay-Dhangar can you please assign this to me

**Comment by Ajay-Dhangar** [comment]
@Hemu21 complete your task asap.

**Comment by Hemu21** [comment]
@Ajay-Dhangar ok I will complete it my today night or morning.

**Comment by Hemu21** [comment]
@Ajay-Dhangar  can you please tell me the node version used in the project i am getting error while running npm start

**Comment by Ajay-Dhangar** [comment]
check out our `package.json` file for all dependencies, scripts, and more...

https://github.com/CodeHarborHub/codeharborhub.github.io/blob/2554ab669a7b65802fb61393de99882d9ca07948/package.json#L95

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar can you please tell me the node version used in the project i am getting error while running npm start

share screenshot I will resolve and suggest you

**Comment by Hemu21** [comment]
![confirm](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/106808387/1042cd76-8043-4f76-9b5d-5b340989cd14)

**Comment by Ajay-Dhangar** [comment]
@Hemu21 please pull the latest main branch into your branch. All errors have been resolved in the main branch.

**Comment by Ajay-Dhangar** [comment]
> ![confirm](https://private-user-images.githubusercontent.com/106808387/346128087-1042cd76-8043-4f76-9b5d-5b340989cd14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODU2MjMsIm5iZiI6MTcyMDE4NTMyMywicGF0aCI6Ii8xMDY4MDgzODcvMzQ2MTI4MDg3LTEwNDJjZDc2LTgwNDMtNGY3Ni05YjVkLTViMzQwOTg5Y2QxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxMzE1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDMyOTNkNjhlZGYyNjk1MDI3NmEzMjE0YWU5YWZlODVhNWZjZTRmYTlhZjMxMzhhZTZjZWM1OGU3MzNkZjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-V5oe_HcnSYW6SclTWzfbfUBokPZIHfXQCRSimF_rVk)
> 
> @Ajay-Dhangar can you please check.

Not all modules were successfully installed. There might be a network issue or some modules could have been skipped, leading to the 'cannot find module' error.

**Comment by Hemu21** [comment]
@Ajay-Dhangar  after installing also it showing same something wrong with sharp

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar after installing also it showing same something wrong with sharp

yes, 

now you can try `npm i sharp`

### resources
- https://www.npmjs.com/package/sharp

### info

`npm i sharp` is a command that installs the sharp Node.js image processing library. Sharp is a popular module that can quickly and efficiently perform image processing tasks within Node.js projects. It can read and convert many common image formats, including JPEG, PNG, GIF, WebP, AVIF, SVG, and TIFF, into smaller, web-friendly images. Sharp can also perform other image operations, such as resizing, rotating, extracting, compositing, and gamma correction.
