### ISSUE TITLE
[Feature Request]: Link missing content

### ISSUE THREAD

**Issue by komal-agarwal5** [CodeHarborHub/codeharborhub.github.io#2304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Content is available in many such places but not linked with the sidebar
I want to link these and make it available

![Screenshot 2024-06-29 164643](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/122633300/630de292-0e79-47fd-9732-f0ed26540c2f)
![Screenshot 2024-06-29 164655](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/122633300/a0ddda75-0cc4-402a-9427-ba88854786f6)
![Screenshot 2024-06-29 164720](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/122633300/649385ca-6667-44cd-ac53-51e8d19d1453)
![Screenshot 2024-06-29 164732](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/122633300/9ed0c252-febd-474f-abe6-37f650d24848)

### Use Case

Availabilty of content

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@komal-agarwal5 please not adding any content to basic-topic because I've already included comprehensive and well-structured details there, such as the content for backtracking. And I will update so, you can try work in other directory

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5 please not adding any content to basic-topic because I've already included comprehensive and well-structured details there, such as the content for backtracking. And I will update so, you can try work in other directory

ok got it
