### ISSUE TITLE
[Feature Request]:  Adding about **space complexity** in DSA page in Basic Concepts.

### ISSUE THREAD

**Issue by GAVINESHWAR** [CodeHarborHub/codeharborhub.github.io#2603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the DSA page there is missing information about the space complexity in the basic concepts topic.

### Use Case

Adding the information about space complexity increase the content of DSA.

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/124431955/11e2ed2e-602b-451c-ba92-82c3745ea24b)

No data about Space Complexity

 I gathered the information to add to space complexity.

@Ajay-Dhangar , assign me this issue make contribution to the project.

Thank you

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@GAVINESHWAR  Could you please provide a detailed explanation of the DSA directory content? We need a comprehensive description that fully aligns with our content structure.

Only for `basic-topics` (folder)

**Comment by GAVINESHWAR** [comment]
> @GAVINESHWAR Could you please provide a detailed explanation of the DSA directory content? We need a comprehensive description that fully aligns with our content structure.
> 
> Only for `basic-topics` (folder)

@Ajay-Dhangar in Dsa page and basic concepts folder the space complexity topic is empty . No  data is added in it in that topic so I would like to add details about space complexity.

**Comment by Ajay-Dhangar** [comment]
> > @GAVINESHWAR Could you please provide a detailed explanation of the DSA directory content? We need a comprehensive description that fully aligns with our content structure.
> > Only for `basic-topics` (folder)
> 
> @Ajay-Dhangar in Dsa page and basic concepts folder the space complexity topic is empty . No data is added in it in that topic so I would like to add details about space complexity.

@GAVINESHWAR I know but you can raise new any issue because we have some ideas for empty files so, you can edit it.
