### ISSUE TITLE
[Feature Request]: Add Google Translator Integration in Footer

### ISSUE THREAD

**Issue by AsmitaMishra24** [CodeHarborHub/codeharborhub.github.io#2617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to request the addition of Google Translator integration into the project. This feature would significantly enhance the user experience by providing seamless translation capabilities.

### Use Case

Accessibility: Non-native speakers would find it easier to use the application.
Global Reach: Expanding the usability of the application to a global audience.
User Convenience: Simplifies the process for users needing translation services within the app.

### Add ScreenShots

![lang](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/146121869/5a186364-1e6c-4f5a-9cc3-1fc6c304a49a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@AsmitaMishra24 you can try https://docusaurus.io/docs/i18n/tutorial for good practices our site is full support it

**Comment by Ajay-Dhangar** [comment]
Google Translator Integration --> level1
Translate with i18n --> level3
