### ISSUE TITLE
[Add]: LeetCode "Add Two Numbers" Solution

### ISSUE THREAD

**Issue by iamanolive** [CodeHarborHub/codeharborhub.github.io#262]
I'd like to add the Python code for the Add Two Numbers problem on LeetCode. 
link to problem: https://leetcode.com/problems/add-two-numbers/description/

**Comment by iamanolive** [comment]
hi @Ajay-Dhangar can i work on this?

**Comment by iamanolive** [comment]
> @Ajay-Dhangar i was assigned this issue, but someone else already submitted a pull request for the same leetcode question that was approved (#301) please clarify

@Ajay-Dhangar

**Comment by Ajay-Dhangar** [comment]
@iamanolive you can be modify this task. If you want to need some changes.
