### ISSUE TITLE
[Feature Request]: adding more social icons in hamburger

### ISSUE THREAD

**Issue by dhairyagothi** [CodeHarborHub/codeharborhub.github.io#2664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/142989448/0d4a66d9-b4e6-4b74-9c53-d968c6932cbe)

want to add more social icons here

### Use Case

adding icons

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@dhairyagothi can you describe

**Comment by dhairyagothi** [comment]
in mobile view side bar contains only github icon i think there should be some more social icons

**Comment by Ajay-Dhangar** [comment]
@dhairyagothi, this issue might not be ideal for now. If we can reference our social profiles, like adding GitHub icons, it could be beneficial, but it's not the best time for this.

**Comment by Ajay-Dhangar** [comment]
So, please close this issue and work on other

**Comment by dhairyagothi** [comment]
Okay
