### ISSUE TITLE
[Feature Request]: Design a blog home page

### ISSUE THREAD

**Issue by komal-agarwal5** [CodeHarborHub/codeharborhub.github.io#2669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to design a blog home page 

### Use Case

Here cards will be used to display title and little info about the blog,from wherein the user can click on the cards to read whichever blog they feel like reading.Data will be mapped into it.

### Benefits

Enhanced feature,ui and readability

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/122633300/9713bb0d-f572-4aa2-ba13-dca1c78a71ed)
kind of like this with cards and data mapping

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@komal-agarwal5, we need to create a new 'Blogs' page that features all our blog posts, complete with images, titles, and descriptions.

**Comment by Ajay-Dhangar** [comment]
### Benefits

- **Level 1:** Basic code with a simple format and layout.
- **Level 2:** Improved layout but doesn't adhere to best practices; may have syntax and styling issues.
- **Level 3:** Professional-grade quality with excellent structure, adherence to best practices, and flawless syntax and styling.

**Comment by komal-agarwal5** [comment]
Ok got it,I will make it like that only
