### ISSUE TITLE
[Feature Request]: Enhancing of CONTRIBUTORS SECTION in our teampage.

### ISSUE THREAD

**Issue by HishitaGupta** [CodeHarborHub/codeharborhub.github.io#2675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhancing of CONTRIBUTORS SECTION in our teampage.

### Use Case

Enhancing of CONTRIBUTORS SECTION in our teampage.

### Benefits

Enhancing of CONTRIBUTORS SECTION in our teampage.

### Add ScreenShots

https://github.com/CodeHarborHub/codeharborhub.github.io/assets/159264060/b1f8e6df-0b63-4f7b-bf55-8ae60d73daca

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@HishitaGupta,

First, create a `ContributorSection` folder in the `src/components` directory

Next, create a file named `index.tsx` within this folder and write your logic and code in it. Export the component at the end.

To use the `ContributorSection` component in `community/team.md`, follow these steps:

1. Import the component at the top of the file:
   ```tsx
   import ContributorSection from '@site/src/components/ContributorSection';
   ```

2. Add the component to the desired location within the file using:
   ```tsx
   <ContributorSection />
   ```

If you need any help, feel free to ask!
