### ISSUE TITLE
[Feature Request]: Addition of Social Media icons in the footer.

### ISSUE THREAD

**Issue by HishitaGupta** [CodeHarborHub/codeharborhub.github.io#2676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of Social Media icons in the footer.

### Use Case

Addition of Social Media icons in the footer.

### Benefits

Addition of Social Media icons in the footer.

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/159264060/c312bd95-51fc-4b5a-b15e-1395dbbe6c3b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@HishitaGupta, we do not need a social icon in the footer.
