### ISSUE TITLE
[Documentation Update]:  add icons in footer

### ISSUE THREAD

**Issue by prachita0504** [CodeHarborHub/codeharborhub.github.io#2719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

![Screenshot 2024-07-08 161655](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/139040702/7d0d821f-261a-45ac-ad0a-e7a39d910479)

### Suggested Change

change them with the app logo's icon as it look more interactive

### Urgency

Medium

### Acknowledgements

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository
- [X] I have read and followed the Contribution Guidelines
- [X] I have followed the code style guidelines of this project
- [X] I have checked for any existing open issues that my pull request may address
- [X] I have ensured that my changes do not break any existing functionality
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently
- [X] I have read the resources for guidance listed below
- [X] I have not used AI-generated content (e.g., ChatGPT, other AI tools)
- [X] I have not used content from existing sites (e.g., text, images)
- [X] I have followed all security rules and only shared trusted resources

**Comment by Ajay-Dhangar** [comment]
@prachita0504, we do not need a social icon in the footer. Please go ahead and raise a new issue because we want to close this issue.
