### ISSUE TITLE
[Feature Request]:  Add scroll down to progress bar

### ISSUE THREAD

**Issue by chaanakyaaM** [CodeHarborHub/codeharborhub.github.io#2755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a website progress indicator bar.

### Use Case

It helps users to show how far the website has been scrolled.

### Benefits

Improves the overall website's UI and make it look professional.

### Add ScreenShots

![Screenshot (345)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/131477601/b1a4a84a-127d-4bb6-a229-b14728103694)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@chaanakyaaM, this approach isn't suitable for our project. While it might be helpful in some contexts, it doesn't align with our platform's goals as an edu-tech site. Adding a scroll-down progress bar isn't ideal. Please create a new issue.
