### ISSUE TITLE
[Feature Request]: Adding HTML roadmap

### ISSUE THREAD

**Issue by dhairyagothi** [CodeHarborHub/codeharborhub.github.io#2761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i would like to add HTML roadmap

### Use Case

adding html roadmap

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@dhairyagothi, you need to go to `page/roadmap` and create a new folder (e.g., `page/roadmap/html`). In this new folder, create an `index.tsx` file and write all the source code there. You can also create additional components and place them in this directory as needed.

**Comment by dhairyagothi** [comment]
okay @Ajay-Dhangar
