### ISSUE TITLE
[Feature]: `Contact us` page cannot Accessable 

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#2796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello @Ajay-Dhangar ,
- In this project `contact us` form after send the button click cannot form `cleared`.
- If the success to clear the form. this is can be user expecting behaviour.

### Use Case

![Screenshot from 2024-07-09 13-58-10](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/121082414/7b594518-fcd3-4e86-b1cf-aea79ba9b01f)

- In after sended the message clear the form

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, you can try to address both issues in a single Pull Request. Please ensure all bugs are resolved and enhance the UI/UX. If you do a good job, I will assign you a good level.
