### ISSUE TITLE
[Feature Request]: Add counter to The numbers on loading landing page

### ISSUE THREAD

**Issue by sau-mili** [CodeHarborHub/codeharborhub.github.io#2814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The numbers displayed with come as counter until reached the value

### Use Case

Better UI

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/146661411/9dd86494-39fa-4576-af00-3efbec904e04)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@sau-mili, the issue at https://github.com/CodeHarborHub/codeharborhub.github.io/issues/2814 already exists, so please consider working on another.
