### ISSUE TITLE
[Feature Request]: Add CSS Roadmap

### ISSUE THREAD

**Issue by zalabhavy** [CodeHarborHub/codeharborhub.github.io#2857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add CSS roadmap page.

### Use Case

Knowledge .

### Benefits

Learning

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@Ajay-Dhangar Please assign me this task !

Thank You !

**Comment by Ajay-Dhangar** [comment]
@zalabhavy, issue already exist #2838
