### ISSUE TITLE
[Feature Request]: Add a repo docs

### ISSUE THREAD

**Issue by root-0101** [CodeHarborHub/codeharborhub.github.io#2901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As adding a "repo docs" will be great feature, in this we have a category wise doc that includes some great github repository related to that topic. 

### Use Case

Example: let's say we have a web-dev category so, this page contains a list of some awesome github repo on web-dev and so on. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@root-0101, we would prefer not to include it. However, if you decide to share repos, please ensure it focuses on the best practices for learning purposes and maintaining high standards.
