### ISSUE TITLE
[Feature]: Add the Carrer page 

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#2918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- In this project footer section has mention `career` i want to add career page.
- please assign me.

### Use Case

- Add the career page advising page..

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, think of your work as a branching tree structure. For example, the `/career` page would contain various categories such as jobs and internships. When a user clicks on one of these categories, it would lead them to specific pages like `/career/jobs` or `/career/internships`.
