### ISSUE TITLE
[Feature Request]: Add Social media icon in footer

### ISSUE THREAD

**Issue by heli0707** [CodeHarborHub/codeharborhub.github.io#2986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/3c321e85-0bdf-4d79-87bc-97aaea4b91c6)

To add social media icons in the footer, include the icons for platforms like Facebook, Twitter, and Instagram at the bottom of your webpage. Make sure they are clickable and link to your social media profiles.

![Screenshot (177)](https://github.com/user-attachments/assets/4365936e-72a8-4bc7-a58f-eecfc6ce5eb3)
something like this 

### Use Case

Adding social media icons in the footer allows visitors to easily find and follow your social media profiles, enhancing your online presence and engagement. It also provides a professional touch to your website, showcasing your active participation on social platforms.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@heli0707, thank you for your contribution! At this time, we do not need social icons in the footer. However, I encourage you to raise new issues or suggest other improvements. I welcome your contributions to my project.
