### ISSUE TITLE
[Add]: LeetCode Median of Two Sorted Arrays Solution

### ISSUE THREAD

**Issue by AmrutaJayanti** [CodeHarborHub/codeharborhub.github.io#313]
Please assign me this task under GSSOC'2024

**Comment by Ajay-Dhangar** [comment]
Please follow our structure, similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1), to ensure better understanding for everyone. And [live preview](https://www.codeharborhub.live/dsa-solutions/lc-solutions/0000-0099/two-sum)
