### ISSUE TITLE
[Feature]: Adopt `LiveEditor theme` 

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#3197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- `/LiveEditor/` page `live editor` only dark mode change to adopt website theme.
- please assign me.

### Expected work

![Screenshot from 2024-07-14 12-11-51](https://github.com/user-attachments/assets/e3156a21-11a4-4a12-b7a1-f5de38acc6f1)

### Actual work
![Screenshot from 2024-07-14 12-12-23](https://github.com/user-attachments/assets/9e8292d5-2d0f-4ecc-8d1b-fac37181e204)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, following dark and light mode
