### ISSUE TITLE
[Feature Request]: Adding a preloader to the website.

### ISSUE THREAD

**Issue by happyrao78** [CodeHarborHub/codeharborhub.github.io#3206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding the preloader using react framer motion library.

### Use Case

Will enhance the ui of website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Hi @happyrao78,

Thank you for suggesting the addition of a preloader using the React Framer Motion library. While this is a great feature, we need to ensure it doesn't impact our site's **performance** negatively. If you can **optimize** it to avoid any performance issues, please proceed with the implementation.
