### ISSUE TITLE
🌟Feature : Implement "Realtime Star Counting" Functionality for project!

### ISSUE THREAD

**Issue by aslams2020** [CodeHarborHub/codeharborhub.github.io#3214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Ajay-Dhangar ,

I would like to propose enhancing the "GIthub" Icon in Navbar by adding a **GitHub star button with Real-Time Star Count** **functionality.**
 This will provide users with easier access to **"Star the Repository"** directly from any page of the website. 

![image](https://github.com/user-attachments/assets/9f1880db-453a-4572-beb1-1623810b7d8c)

### Here's what I plan to do:
1. **Replace the existing GitHub logo** in the navbar **with a new button** that **integrates the "GitHub API" to fetch and display the current star count of the repository.**
Here's how it will look and work - 

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/815fc3f7-bd58-4f0b-b20f-2a6e9dd58be1)

2. Ensure the button **redirects users to our repository's GitHub page** when clicked, **allowing them to Star the repository directly.**
3. Implement a **visual design that seamlessly integrates with our navbar's existing style and layout.**

This enhancement will improve user engagement and visibility of our repository's popularity.
Please assign me under GSSOC'24.
Thankyou!

### Use Case

It will make easy for the users to directly Star the Repository..And Instantly see the Dynamically changing stars count in the navbar.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@aslams2020, we already display the GitHub repo star count on the home page. Including it in the navbar as well is not a best practice.

**Comment by aslams2020** [comment]
@Ajay-Dhangar Oh, okay understood.
Thankyou for the response!
