### ISSUE TITLE
Add Icons to Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [CodeHarborHub/codeharborhub.github.io#3220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to add icons to Footer
Can you assign me this issue under GSSOC'24

### Use Case

![IMG_20240714_175741](https://github.com/user-attachments/assets/6d8332f8-666c-4c87-aea9-24a893af2f21)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@sailaja-adapa, can you open new issue we don't need any icon in footer
