### ISSUE TITLE
[Feature Request]: Making substantial documentation update towards missing LC problem numbers 194, 195, 196 in DSA solutions folder

### ISSUE THREAD

**Issue by aaryaanshh** [CodeHarborHub/codeharborhub.github.io#3230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Describe the new feature or enhancement you'd like to see:
I propose adding documented solutions for the following LeetCode problems to the project repository:

Problem 194: Transpose File
Problem 195: Tenth Line
Problem 196: Delete Duplicate Emails

This involves providing clear, commented code solutions along with explanations of the approaches used for each problem.

### Use Case

Use Case:
For a developer working on shell scripting or data manipulation tasks, having access to well-documented solutions for these problems can significantly enhance their productivity. For example, they can use the solution for problem 194 to transpose data files, the solution for problem 195 to extract specific lines from a file, and the solution for problem 196 to clean up email data by removing duplicates. These solutions provide practical, real-world applications that can streamline various tasks in data processing and manipulation.

### Benefits

What benefits would this feature bring to the project or community?

Practical Utility: Provides practical implementations for common data manipulation tasks using shell scripting.
Educational Resource: Enhances project documentation with detailed examples of file operations and data processing techniques.
Community Engagement: Encourages collaborative learning and contributions, fostering a stronger developer community around shell scripting and data manipulation.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by aaryaanshh** [comment]
Dear @Ajay-Dhangar Sir.

I am writing to request the assignment of three problem solutions under LEVEL-3/2 for GSSoC 2024. Given that I will be providing documentation for three solutions simultaneously, I believe this classification is appropriate.

Thank you for your consideration.

**Comment by Ajay-Dhangar** [comment]
> Dear @Ajay-Dhangar Sir.
> 
> I am writing to request the assignment of three problem solutions under LEVEL-3/2 for GSSoC 2024. Given that I will be providing documentation for three solutions simultaneously, I believe this classification is appropriate.
> 
> Thank you for your consideration.

@aaryaanshh, read https://github.com/orgs/CodeHarborHub/discussions/1028 carefully

**Comment by aaryaanshh** [comment]
> > Dear @Ajay-Dhangar Sir.

Okay sir, thanks for clarifying.
