### ISSUE TITLE
Styles Issue (JS-R1000) : Found multiple import of the same path

### ISSUE THREAD

**Issue by Ajay-Dhangar** [CodeHarborHub/codeharborhub.github.io#3269]
## Is there an existing issue for this?

- [X] I have searched the existing issues

### 'react-icons/fa' imported multiple times

📝 `src/pages/contact/index.tsx`

```tsx
import PhoneInput from "react-phone-input-2";
import "react-phone-input-2/lib/style.css";
import { FaYoutube } from "react-icons/fa";
import { FaDiscord } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import { FaLinkedin } from "react-icons/fa";
import Popup from "../popup/popup";
```

📝 `src/pages/contact/index.tsx`

```tsx
import { motion } from "framer-motion";
import PhoneInput from "react-phone-input-2";
import "react-phone-input-2/lib/style.css";
import { FaYoutube } from "react-icons/fa";
import { FaDiscord } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import { FaLinkedin } from "react-icons/fa";
```

📝 `src/pages/contact/index.tsx`

```tsx
import { FaYoutube } from "react-icons/fa";
import { FaDiscord } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import { FaLinkedin } from "react-icons/fa";
import Popup from "../popup/popup";
import axios from 'axios'
```

## Expected behaviour

It is always recommended to group all imports of a single path or source in a single import declaration. These usually happen in a codebase when multiple developers are working on the same codebase. It helps improve code refactoring and code readability as well.

### BAD PRACTICE

```js
// <!-- index.js -->

import calc from './calc.js'
import { add } from './calc.js'

console.log(add(1, 2))
```

### RECOMMENDED

```js
// <!-- index.js -->

import calc,  { add }  from './calc.js'

console.log(add(1, 2))
```

## Add ScreenShots

NA

## On which device are you experiencing this issues?

Android, Linux, Chrome, Windows

## Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by vansh-codes** [comment]
I would like to fix this issue, please assign me! @Ajay-Dhangar

**Comment by Ajay-Dhangar** [comment]
@vansh-codes: Only make changes to the code according to the suggestions.

**Comment by vansh-codes** [comment]
> @vansh-codes: Only make changes to the code according to the suggestions.



> @vansh-codes: Only make changes to the code according to the suggestions.

@Ajay-Dhangar I have fixed the issue and raised a PR, please review it.
Also no other files had this issue rather then the one specified by you, if any you can let me know

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/3329
