### ISSUE TITLE
[Feature Request]: Styling and hover effect to the Showcase cards 

### ISSUE THREAD

**Issue by Damini2004** [CodeHarborHub/codeharborhub.github.io#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The requested feature involves enhancing the visual appeal and interactivity of the showcase cards on the website by adding refined styling and hover effects. Showcase cards typically display featured content, such as restaurant listings in the context of a Zomato clone, and improving their design can significantly enhance the user experience.

### Use Case

Improved User Experience:

Attractive and interactive showcase cards draw users’ attention, encouraging them to explore more content.
Hover effects provide immediate feedback, making the interface feel more responsive and user-friendly.
Increased Engagement:

Visually appealing and interactive elements can lead to higher user engagement, as users are more likely to click on cards that look appealing and respond to their actions.
Professional Appearance:

Well-designed cards with thoughtful styling and interactions contribute to a professional and polished appearance, enhancing the overall credibility of the website.
Consistent Brand Identity:

Consistent styling ensures that all elements of the website contribute to a cohesive brand identity, making the site more memorable and trustworthy.

### Benefits

Enhanced Aesthetic Appeal:

Well-styled cards with subtle hover effects add to the visual richness of the website, making it more appealing to users.
Better User Interaction:

Interactive elements with clear visual feedback improve user interaction, making the site more intuitive and engaging.
Increased Time on Site:

Engaging showcase cards can encourage users to spend more time on the site, exploring different listings and features.
Higher Conversion Rates:

Attractive and interactive cards can lead to higher conversion rates, whether the goal is to get more restaurant bookings, user registrations, or other key actions.

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Sure, but apply the style only to the Showcase cards, not to other elements. Use the full path (parent > child > ...) to ensure the styles are unique to the component and properly applied.
