### ISSUE TITLE
Enhancing the UI of "Loved by many users" sections.

### ISSUE THREAD

**Issue by sharmi4590** [CodeHarborHub/codeharborhub.github.io#341]
This section is very simple and improving it world enhance the user experience as well.It will also save a lot of space in the webpage and is efficient when there are more user reviews as well.

This is my previous work with the testimonials.

![Screenshot (398)](https://github.com/CodeHarborHub/codeharborhub/assets/102676949/137e93b7-fe1a-428f-b8e8-800a13793500)
![Screenshot (399)](https://github.com/CodeHarborHub/codeharborhub/assets/102676949/92ce5957-a629-49bf-ac11-c8b3a4458c64)
On hovering the card it rotates.

**Comment by sharmi4590** [comment]
Hey @Ajay-Dhangar You mentioned some changes to my PR, do I need to raise another PR after the changes as that PR was closed?

**Comment by sharmi4590** [comment]
Hey @Ajay-Dhangar

**Comment by Ajay-Dhangar** [comment]
@sharmi4590 I apologize for closing your PRs without an explanation. The UI doesn't meet our requirements, and I have been overwhelmed with tasks. Sorry for the inconvenience.

**Comment by Ajay-Dhangar** [comment]
You can try working on other tasks, and I will appreciate your efforts. And I closed this issue
