### ISSUE TITLE
[Bug]: FAQ in dark mode hover show green color that not matches the theme.

### ISSUE THREAD

**Issue by zalabhavy** [CodeHarborHub/codeharborhub.github.io#3412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/6736f75a-f1e8-4d1d-864a-02c97be4ed03)

**I will make that hover color like** 

![image](https://github.com/user-attachments/assets/90cb314a-8c28-4acd-8e36-91cc79068700)

### Expected behavior

NA

### Add ScreenShots

NA

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@zalabhavy, please adjust the width as the current layout does not look good. You might consider using the full width or arranging the FAQ section in a two-column grid for better presentation.
