### ISSUE TITLE
[Feature Request]: Implementing Bellman Ford algorithm in C++ under DSA folder.

### ISSUE THREAD

**Issue by sjain1909** [CodeHarborHub/codeharborhub.github.io#3487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am requesting the implementation of the Bellman-Ford algorithm in C++ for the Data Structures and Algorithms (DSA) folder. The Bellman-Ford algorithm computes the shortest paths from a single source vertex to all other vertices in a weighted graph. It can handle graphs with negative weight edges, which many other shortest path algorithms cannot.

### Use Case

This feature would be a valuable addition to the DSA folder as it provides an essential algorithm for handling graphs with negative weights, a common requirement in various applications. A specific use case for this feature would be in educational settings where students learn about graph algorithms, particularly those dealing with negative weights. 

### Benefits

Implementing the Bellman-Ford algorithm in the DSA folder would enhance the repository by adding a crucial graph algorithm, aiding in educational purposes, and providing developers with a reliable solution for shortest path computations in graphs with negative weights.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sjain1909** [comment]
@Ajay-Dhangar sir, kindly assign me this issue under GSSOC'24.

**Comment by Ajay-Dhangar** [comment]
Hi @sjain1909 

Here are some [Guidelines for Writing DSA Problem Solutions](https://github.com/orgs/CodeHarborHub/discussions/3369) for your reference. Please ensure that all your contents follow these guidelines so that we can maintain the quality of the solutions at a high level.

Feel free to ask if you have any questions.
