### ISSUE TITLE
[Feature Request]: Implementing Greedy Algorithm for Graph Optimization in C++ under DSA folder.

### ISSUE THREAD

**Issue by sjain1909** [CodeHarborHub/codeharborhub.github.io#3488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose implementing a greedy algorithm specifically designed for graph optimization problems, such as finding a minimum spanning tree or the shortest path. This feature would enable users to apply a greedy approach to various graph-related tasks, improving efficiency and usability.

### Use Case

This feature would enhance my use of the project by allowing for quicker solutions to common graph problems. For instance, in a scenario where we need to find the shortest path in a network of nodes (such as transportation routes), this greedy approach can significantly reduce computation time compared to other algorithms.

### Benefits

Implementing the greedy algorithm for graph optimization will significantly enhance project efficiency by providing faster solutions to common problems like minimum spanning trees and shortest paths. This feature will make the tool more user-friendly, allowing developers of varying skill levels to easily apply graph algorithms. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sjain1909** [comment]
@Ajay-Dhangar sir, kindly assign me this issue under GSSOC'24.

**Comment by sjain1909** [comment]
@Ajay-Dhangar sir, kindly assign me this issue under GSSOC'24.

**Comment by Ajay-Dhangar** [comment]
Please remember to follow our [Guidelines for Writing DSA Problem Solutions](https://github.com/orgs/CodeHarborHub/discussions/3369)
