### ISSUE TITLE
[Feature Request]: Add `MongoDB Tutorials` Course

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#3504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello  @Ajay-Dhangar ,

- If i want to add `Tutorials` for `mongoDB` course.
- please assign me.

### Use Case

![Screenshot from 2024-07-17 17-58-29](https://github.com/user-attachments/assets/89116f8d-a0de-42e7-b62c-b1b8adb03457)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sivaprasath2004** [comment]
@Ajay-Dhangar could you please assign me..

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, to achieve a good level of content, you should utilize our features to enhance your content for better comprehension and interactive learning experiences for our learners.

Here are some essential resources to guide you in creating good content:
- https://codeharborhub.github.io/community/features
- https://codeharborhub.github.io/docs/javascript/intro-js
- https://github.com/CodeHarborHub/codeharborhub.github.io/blob/main/docs/javascript/intro-js.md?plain=1
