### ISSUE TITLE
Add tutorial in Node.js in courses

### ISSUE THREAD

**Issue by pavitraag** [CodeHarborHub/codeharborhub.github.io#3529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to add tutorials in node.js course

### Add ScreenShots

<img width="941" alt="image" src="https://github.com/user-attachments/assets/0ab8d8d4-c0d7-4d58-a7cb-4a8a3e447346">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by shivay-coding** [comment]
The CodeHarborHub Node.js course is a great resource for aspiring Node.js developers. This course provides a high-level overview of Node.js, and it covers many fundamental concepts such as Node.js features, event loop, package management, and more. I found the course to be informative and helpful.

However, I think the course section should be closed. I think it's better to have industry experts with experience write courses for our website, or we could write the content ourselves in this section. In this way, we can ensure that the courses are high quality and provide valuable information to our users.

**Comment by Ajay-Dhangar** [comment]
@pavitraag, please work on an easy task because we need to focus on our structure and can't afford complexity.
