### ISSUE TITLE
[Feature Request]: want to add Add Solution for a problem 244 (Premium)

### ISSUE THREAD

**Issue by pallasivasai** [CodeHarborHub/codeharborhub.github.io#3530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

0244- Shortest Word Distance II

The problem provides us with the task of designing a data structure that must be able to compute the shortest distance between any two distinct strings within an array of strings. This implies that we first need to initialize the data structure with an array of strings, which we'll refer to as wordsDict. Once initialized, we should be able to query this data structure with two different strings, and it should return the smallest possible index difference between these two strings within the wordsDict array.

This could be visualized as an array where we want to find the minimum distance between two elements, where the elements are the positions of the words we're interested in. For example, if wordsDict is ["practice", "makes", "perfect", "coding", "makes"], and we query for the distance between "coding" and "practice", the returned value should be 3, as the closest "practice" to "coding" is three indices away.

### Use Case

Let's demonstrate how the WordDistance class and its methods work using a simple example.

Suppose our wordsDict is ["the", "quick", "brown", "fox", "quick"]. We initialize the WordDistance class with this list of strings. During the initialization process, the class builds the hash map self.d which will contain:

"the" -> [0]
"quick" -> [1, 4]
"brown" -> [2]
"fox" -> [3]
Now, let's say we want to find the shortest distance between the words "brown" and "quick". We call the shortest method with these two words. Here's what happens inside this method:

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@pallasivasai, please follow our DSA structure.

````mdx
---
id: enter-id-for-routes
title: Title of Problem
sidebar_label: Number of Problem
tags: [tag1, tag2, ...., tagn]
description: Write description for SEO in few words and in only string and can't use any HTML tags in this line
sidebar_position: enter position number
---

## Problem Statement 

### Problem Description

<!-- Content here -->

### Examples

<!-- Problem Examples here -->

### Constraints

<!-- Problem Constraints here -->

## Solution of Given Problem

### Intuition and Approach

<!-- Content here -->

### Approaches

<!-- Content here -->

#### Codes in Different Languages

<Tabs>
  <TabItem value="JavaScript" label="JavaScript" default>
  <SolutionAuthor name="@username"/>
   ```javascript
    // code here
    ```

  </TabItem>
  <TabItem value="TypeScript" label="TypeScript">
  <SolutionAuthor name="@username"/> 
   ```typescript
    // code here
    ```

  </TabItem>
  <TabItem value="Python" label="Python"> 
  <SolutionAuthor name="@username"/>
   ```python
    # code here
    ```

  </TabItem>
  <TabItem value="Java" label="Java">
  <SolutionAuthor name="@username"/>
   ```java
    // code here
    ```
  </TabItem>
  <TabItem value="cpp" label="C++">
  <SolutionAuthor name="@username"/>
   ```cpp
    // code here
    ```
  </TabItem>  
</Tabs>

### Complexity Analysis

<!-- Content here -->

## Video Explanation of Given Problem

<Tabs>
  <TabItem value="en" label="English">
    <Tabs>
      <TabItem value="javascript" label="JavaScript">
        <LiteYouTubeEmbed
          id="video_id"
          params="autoplay=1&autohide=1&showinfo=0&rel=0"
          title="Problem Explanation | Solution | Approach"
          poster="maxresdefault"
          webp 
        />
      </TabItem>
      <TabItem value="python" label="Python">
        <LiteYouTubeEmbed
          id="video_id"
          params="autoplay=1&autohide=1&showinfo=0&rel=0"
          title="Problem Explanation | Solution | Approach"
          poster="maxresdefault"
          webp 
        />
      </TabItem>
      <TabItem value="java" label="Java">
        <LiteYouTubeEmbed
          id="video_id"
          params="autoplay=1&autohide=1&showinfo=0&rel=0"
          title="Problem Explanation | Solution | Approach"
          poster="maxresdefault"
          webp 
        />
      </TabItem>
    </Tabs>
  </TabItem>

  <TabItem value="hi" label="Hindi">
    <LiteYouTubeEmbed
      id="video_id"
      params="autoplay=1&autohide=1&showinfo=0&rel=0"
      title="Problem Explanation | Solution | Approach"
      poster="maxresdefault"
      webp 
    />
  </TabItem>
</Tabs>

---

<h2>Authors:</h2>

<div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '10px'}}>
{['github_username'].map(username => (
 <Author key={username} username={username} />
))}
</div>
````


### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.
