### ISSUE TITLE
[Feature Request]: Showcase custom made CSS buttons

### ISSUE THREAD

**Issue by Ridhima10** [CodeHarborHub/codeharborhub.github.io#3591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add my custom made buttons from raw CSS in the showcase page
There are 6 buttons with cool animations and a toggle button also

### Use Case

They can be used by fellow programmers in their projects

### Benefits

They are easy to use and they enhance the UI

### Add ScreenShots

https://github.com/user-attachments/assets/0a0755de-ec4c-4522-a188-ad4a1095a370

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Ridhima10, try button number 2.
