### ISSUE TITLE
[Feature]: Add `Bootstrap for Beginners`  course

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#3600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello @Ajay-Dhangar 

- If i want implement the new `Bootstrap` Course
- please assign me

### Use Case

[Screencast from 2024-07-19 21-56-59.webm](https://github.com/user-attachments/assets/0afdae55-9b0f-4702-a886-dd87ad60b5fc)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, the content is already large and our docker image can't be loaded. Therefore, we don't need to add the course directly; instead, we need to use the API or back-end.
