### ISSUE TITLE
[Feature]:  Add the `Firebase Course`

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#3625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello @Ajay-Dhangar ,

- In this project `/course` section if the `firebase` course click the course cannot open `404 page not found`.
- Could you please assign me.
- i will add on the course.
- please assign me..

### Use Case

[Screencast from 2024-07-20 11-32-08.webm](https://github.com/user-attachments/assets/2f98f110-f9b9-4c89-83d7-170aef7427af)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, after some time we create, but at this time you can work on other tasks instead of course creation because we need to maintain our content in a very structured way and avoid creating complexity between us.
