### ISSUE TITLE
[Feature Request]: New Blog named Getting Stated with Serverless Architecture using AWS Lambda

### ISSUE THREAD

**Issue by Nayanika1402** [CodeHarborHub/codeharborhub.github.io#3629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. Introduction
2. Key Concepts
3. Setting Up AWS Lambd
4. Writing and Deploying Lambda Functions
5. Lambda Execution Model
6. Managing Lambda Functions
7. Advanced Topics
8. Performance and Scaling
9. Testing and Debugging
10. Real-World Examples
11. Conclusion

### Use Case

In tech field.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Nayanika1402, I assign you a good level, so I need in-depth and easy-to-understand content for users of all levels.
