### ISSUE TITLE
[Bug]: Extra space at navbar

### ISSUE THREAD

**Issue by mehrun171** [CodeHarborHub/codeharborhub.github.io#3669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is an extra padding space at NAVBAR...i want to remove it

### Expected behavior

Removing the extra space at  navbar

### Add ScreenShots

![Screenshot 2024-07-20 212010](https://github.com/user-attachments/assets/32241332-43af-48b9-9bd5-d559c0d87262)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Hi @mehrun171. This isn't empty space; it's for auto ads. The space is automatically created to place the ads.

**Comment by Ajay-Dhangar** [comment]
So, you can try another issue.
