### ISSUE TITLE
[Feature Request]: Adding Kotlin language course under DOC folder. 

### ISSUE THREAD

**Issue by sjain1909** [CodeHarborHub/codeharborhub.github.io#3770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose adding a comprehensive Kotlin language course under the DOC folder. Kotlin is a modern, statically typed programming language that is fully interoperable with Java and has been officially supported for Android development. This course will cover the following topics to help users learn Kotlin effectively:

1. Introduction to Kotlin
2. Setting up the development environment
3. Basic syntax and types
4. Control flow (if, when, loops)
5. Functions and lambdas
6. Collections and arrays
7. Object-oriented programming (classes, objects, inheritance)
8. Null safety and exceptions
9. Coroutines for asynchronous programming
10. Building Android applications with Kotlin
11. Best practices and advanced topics

### Use Case

This feature would enhance the project by providing a structured guide for learning Kotlin, which is essential for modern Android development and other JVM-based projects. For example, developers transitioning from Java to Kotlin or beginners starting with Android development will benefit from this course.

### Benefits

Adding a Kotlin course under the DOC folder will provide a comprehensive and structured guide to help users learn Kotlin effectively. This will enhance the project's documentation, making it a valuable resource for developers transitioning from Java or starting with Android development. Additionally, it will attract more users to the project, boosting its visibility and utility in the Kotlin development community.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sjain1909** [comment]
@Ajay-Dhangar sir, kindly assign me this issue under GSSOC'24.

**Comment by Ajay-Dhangar** [comment]
@sjain1909, the level I assign you will be based on the quality of your content. To earn a good level, your content should follow all of our guidelines and resources. It should also include all relevant features and provide clear and concise explanations of the topic at hand.
