### ISSUE TITLE
[Feature Request]:  Adding Rust language tutorial under DOC folder. 

### ISSUE THREAD

**Issue by sjain1909** [CodeHarborHub/codeharborhub.github.io#3772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose adding a comprehensive Rust language tutorial under the DOC folder. Rust is a systems programming language known for its performance, reliability, and memory safety. This tutorial will cover the following topics to help users get started and effectively use Rust:

1. Introduction to Rust
2. Setting up the development environment
3. Basic syntax and types
4. Control flow (if, match, loops)
5. Functions and closures
6. Ownership and borrowing
7. Structs and enums
8. Error handling
9. Modules and packages (Cargo)
10. Best practices and advanced topics

### Use Case

This feature would enhance the project by providing a structured guide for learning Rust, which is essential for system-level programming, web development, and other performance-critical applications. For example, developers looking to build safe and efficient software will benefit from this tutorial.

### Benefits

Adding a Rust tutorial under the DOC folder will provide a comprehensive and structured guide for users to learn Rust efficiently. This will enhance the project's documentation, making it a valuable resource for developers interested in Rust. Additionally, it will attract more users to the project, boosting its visibility and utility in the Rust development community.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sjain1909** [comment]
@Ajay-Dhangar sir, kindly assign me this issue under GSSOC'24.

**Comment by Ajay-Dhangar** [comment]
@sjain1909, the table of contents you shared for a Rust tutorial looks good. Based on the quality of the content, we can increase your level to level3. 

We recommend that you add some more advanced topics to the tutorial, such as Rust's asynchronous programming model, and unsafe code. 

We are excited to see what you do next, and thank you for contributing to the CodeHarborHub documentation.

**Comment by sjain1909** [comment]
Sure @Ajay-Dhangar sir !
