### ISSUE TITLE
📝[Docs]: Adding Installation and Setup Guide

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [CodeHarborHub/codeharborhub.github.io#3779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I've noticed your project lacks a Installation and Setup Guide, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully

### Suggested Change

I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

I've done a readme file for another project, you can check my profile, i always give my best.
You see my work [HERE](https://github.com/singodiyashubham87/Draw-it-out?tab=readme-ov-file#contributing-guidelines)
Can you assign me this task?

Thank u @Ajay-Dhangar

### Urgency

High

### Acknowledgements

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository
- [X] I have read and followed the Contribution Guidelines
- [X] I have followed the code style guidelines of this project
- [X] I have checked for any existing open issues that my pull request may address
- [X] I have ensured that my changes do not break any existing functionality
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently
- [X] I have read the resources for guidance listed below
- [X] I have not used AI-generated content (e.g., ChatGPT, other AI tools)
- [X] I have not used content from existing sites (e.g., text, images)
- [X] I have followed all security rules and only shared trusted resources

**Comment by Ajay-Dhangar** [comment]
Hi @iamkanhaiyakumar,

Thank you for reaching out! As a GSSoC 2024 participant, you are keen on contributing meaningfully. However, we have already every resource for new contributors that should help with the issue you’re describing:

- [Contributing Guide](https://github.com/CodeHarborHub/codeharborhub.github.io/blob/main/CONTRIBUTING.md)
- [Developer Documentation](https://github.com/CodeHarborHub/codeharborhub.github.io/blob/main/Learn.md)
- [Features](https://codeharborhub.github.io/community/features)
- [Contributing Guidelines](https://codeharborhub.github.io/community/contributing-guidelines)
- [Support](https://codeharborhub.github.io/community/supports/)

Please review these resources, as they might help resolve your issue. If you still have questions after reviewing, and raise new issues and work on it.
