### ISSUE TITLE
I want to add a newsletter subscription section to the footer.

### ISSUE THREAD

**Issue by lovelymahor** [CodeHarborHub/codeharborhub.github.io#3831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a newsletter subscription section in the footer with:

An inviting text.
An input field for email addresses.
A "Subscribe" button.
Proper validation and feedback for successful subscription.

### Use Case

The design of the newsletter subscription section should be consistent with the website’s overall style.
Ensure the process is user-friendly and accessible.

### Benefits

nhanced Engagement: Boosts user retention and interaction through regular updates.
Marketing Reach: Expands reach by creating a direct communication channel with users.

### Add ScreenShots

![Screenshot (264)](https://github.com/user-attachments/assets/9be7cceb-4860-4734-884c-479837a85b0e)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by lovelymahor** [comment]
Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by Ajay-Dhangar** [comment]
@lovelymahor, try link: https://www.linkedin.com/newsletters/advance-development-and-coding-7030185990174515200 for newsletter subscription
