### ISSUE TITLE
[Feature Request]: Implement the solution in different programming language in algorithms

### ISSUE THREAD

**Issue by jayanththalla** [CodeHarborHub/codeharborhub.github.io#3860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is only a solution code in the C++ not there in different programming language like java python

### Use Case

Adding the solution in different languages

### Add ScreenShots

![image](https://github.com/user-attachments/assets/055c188b-f465-4f0b-98e7-d266f6a95bf0)
please assign me@pa

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by adinathraut** [comment]
hey @Ajay-Dhangar can I work on this?
