### ISSUE TITLE
PRs not counted

### ISSUE THREAD

**Issue by AmrutaJayanti** [CodeHarborHub/codeharborhub.github.io#3919]
#1095 

#1437

#1364

#1284 

#1155 

#911 

#926 

#750 

#586 

Please check them as mentioned these were not counted in Leaderboard

**Comment by AmrutaJayanti** [comment]
#542 also

**Comment by Ajay-Dhangar** [comment]
@AmrutaJayanti, you can create three pull requests, and you can edit any code, but you can only change one character per pull request, such as a single text or whitespace character. I will assign level3 to each of the three pull requests that you open.

**Comment by AmrutaJayanti** [comment]
@Ajay-Dhangar Can I directly raise PRs without raising any issues
