### ISSUE TITLE
[Bug]:  PRs are not being reflected in the leaderboard.

### ISSUE THREAD

**Issue by abckhush** [CodeHarborHub/codeharborhub.github.io#4019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My 4 PRs of this repository are not being reflected. I was told to report to you about this.
https://github.com/GSSoC24/Contributor/issues/499?notification_referrer_id=NT_kwDOB5el6LUxMTUzNDE3NzA1OToxMjczNzg5MjA#issuecomment-2254488360

### Expected behavior

Links to my 4 PRs are:
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1177
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/915
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1020
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/897

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by abckhush** [comment]
@Ajay-Dhangar Kindly look into this matter ASAP.

**Comment by Ajay-Dhangar** [comment]
@abckhush, you can create a new pull request and mention your uncounted pull requests then I'll remerge

**Comment by abckhush** [comment]
As in 4 different PRs ?

**Comment by abckhush** [comment]
@Ajay-Dhangar I have created 4 different PRs. Kindly merge them as soon as possible and add the previous levels. Thankyou!

**Comment by abckhush** [comment]
@Ajay-Dhangar kindly mark the level2 PRs as level 2. Before the guidelines changed all those who contributed had these levels. It would be unfair if they get to retain them while mine are changed. Kindly look into this pls.

**Comment by abckhush** [comment]
Thankyou! On PR#4040 and PR#4041

**Comment by abckhush** [comment]
@Ajay-Dhangar Kindly change the level pls :) On PR https://github.com/CodeHarborHub/codeharborhub.github.io/pull/4042 and PR https://github.com/CodeHarborHub/codeharborhub.github.io/pull/4041

**Comment by abckhush** [comment]
@Ajay-Dhangar Kindly change the levels pls :)

**Comment by abckhush** [comment]
Thankyou :)
