### ISSUE TITLE
[Feature]:  Add to live editor `settings`

### ISSUE THREAD

**Issue by sivaprasath2004** [CodeHarborHub/codeharborhub.github.io#4047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- In this `live Editor ` add the `font size increase`  and more settings like background editor color and font color customizer..
- please assign me..

### Use Case

- In this live editor to settings to click to customize the settings and colors. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, you can also try using an Apple-style window for the output to achieve the best layout and enhance UI/UX.

![image](https://github.com/user-attachments/assets/09aa365a-fd72-4f7e-a788-d80d2f7baffd)

**Comment by sivaprasath2004** [comment]
Hello @Ajay-Dhangar , please give a style information

**Comment by sivaprasath2004** [comment]
sure
