### ISSUE TITLE
[Bug]: Hero section is not responsive.

### ISSUE THREAD

**Issue by nagalakshmi08** [CodeHarborHub/codeharborhub.github.io#4118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The hero section in home page is not responsive. The text is overflowing and not completely visible in small screens.

### Expected behavior

To make the hero section responsible and to make look good in all types of screens.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0a712364-5834-40b6-b839-e0d91b30df31)

Please assign me this issue, I would like to contribute to this project under GSSOC'24.

### On which device are you experiencing this bug?

Android, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Hi, @nagalakshmi08, thanks for bringing this up. I just checked the site on multiple devices, and it's fully responsive. We take pride in our site's mobile friendliness. The issue you're seeing might be introduced by auto ads. Are you able to provide any additional information or screenshots that might help us troubleshoot further?

**Comment by nagalakshmi08** [comment]
> Hi, @nagalakshmi08, thanks for bringing this up. I just checked the site on multiple devices, and it's fully responsive. We take pride in our site's mobile friendliness. The issue you're seeing might be introduced by auto ads. Are you able to provide any additional information or screenshots that might help us troubleshoot further?

Hi, sorry for the misinformation. I think that irresponsiveness came due to improper loading of webpage due to slow internet. Now it is looking fine in my screen.

**Comment by Ajay-Dhangar** [comment]
In the meantime, I would encourage you to try to work on other issues that you can recreate. Many issues are open and waiting for a contributor. I’m sure you would be a valuable asset to this project and we are grateful for your interest in contributing.
