### ISSUE TITLE
[Feature Request]: Add Solution link for LeetCode problem 400

### ISSUE THREAD

**Issue by Saksham2k3s** [CodeHarborHub/codeharborhub.github.io#4197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add Solution link for LeetCode problem 400

### Use Case

As a user of the project repository, I want to have a direct link to the solution for LeetCode problem 400 so that I can quickly access and review the solution.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
There are many DSA problems without solution links. This is a big problem because it means users have to spend extra time searching for solutions. Please add solution links for all DSA problems, so that users can easily access the necessary solutions. @Saksham2k3s, please do the needful.
