### ISSUE TITLE
[GFG]: anshuman's Favourite Numbe

### ISSUE THREAD

**Issue by Saksham2k3s** [CodeHarborHub/codeharborhub.github.io#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add solution for above under leetcode-solution section.

### Use Case

I will provide proper description and comments.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Saksham2k3s Please complete your task otherwise I will close it.
