### ISSUE TITLE
[Feature]: Leetcode  74. Search a 2D Matrix

### ISSUE THREAD

**Issue by ayushchaware08** [CodeHarborHub/codeharborhub.github.io#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a Solution for 74. Search a 2D Matrix Leetcode Question under Leetcode-solution Section.

### Use Case

the viewer will be able to understand the logic behind the Question easily using their preferred Language.

### Benefits

Easy to Understand | Solution in Cpp, Java, Pyhton | Briefly Answered

### Add ScreenShots

NA

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@ayushchaware08 Please complete your task otherwise I will close it.
