### ISSUE TITLE
[Feature Request]: Python docs addition

### ISSUE THREAD

**Issue by Yashgabani845** [CodeHarborHub/codeharborhub.github.io#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding multiple sections of Python documentation

1. Python data type
2. Python String
3. Python if...else and switch
4. Python loops

### Use Case

documentation of python

### Benefits

Adding Quality Documentation 
and also addig multiple sections(please consider it)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Yashgabani845** [comment]
@Ajay-Dhangar please assign me this issue 
i have completed previous issue

**Comment by Yashgabani845** [comment]
@Ajay-Dhangar my all previous issue are done plaease assign me tjhis issue

**Comment by amanjaiswal7236** [comment]
Hey @Ajay-Dhangar can i work on this?

**Comment by Yashgabani845** [comment]
@amanjaiswal7236 please work over any other issue i already researched for this

**Comment by amanjaiswal7236** [comment]
okk @Yashgabani845
