### ISSUE TITLE
[Feature Request]: I would like to add solution for 31. Next Permutation

### ISSUE THREAD

**Issue by thevijayshankersharma** [CodeHarborHub/codeharborhub.github.io#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add solution for 31. Next Permutation

### Use Case

I will provide proper description and comments.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@thevijayshankersharma Please limit the number of issues created per day to 4-5.

**Comment by thevijayshankersharma** [comment]
> @thevijayshankersharma Please limit the number of issues created per day to 4-5.

@Ajay-Dhangar from now onwards I will. But atleast give level 2 label for medium problem.

**Comment by thevijayshankersharma** [comment]
@Ajay-Dhangar or else I will raise for 2 problems of medium give it level 3.

**Comment by Ajay-Dhangar** [comment]
@thevijayshankersharma I know your content is good, but it needs more improvement and better explanation. Based on the current level, I can't assign a level 3 rating. Level 3 is for very advanced work, like that of a professional. This documentation page should not be rated at level 3 as the code is more suited to level 2. The basics are aligned with level 1. I have already completed the setup and provided resources on how to write, so you only need to write the content. This is similar to a simple markdown file implementation. Based on GSSOC'24 guidelines, I can't assign a level 3 rating

**Comment by thevijayshankersharma** [comment]
@Ajay-Dhangar l got it but as you said it's suited for level 2 but you have given me level 1 label to my most PRs. Could you change it to level 2 ??
