### ISSUE TITLE
[Feature Request]:I would like to add solution for 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by thevijayshankersharma** [CodeHarborHub/codeharborhub.github.io#532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add solution for 33. Search in Rotated Sorted Array

### Use Case

I will provide proper description and comments.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@thevijayshankersharma Please limit the number of issues created per day to 4-5.

**Comment by Yashgabani845** [comment]
@Ajay-Dhangar it is good approch 
i hope @thevijayshankersharma you cooperate

**Comment by thevijayshankersharma** [comment]
> @Ajay-Dhangar it is good approch i hope @thevijayshankersharma you cooperate

yeah I will
