### ISSUE TITLE
[Feature Request]: I would like to add solution for 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by thevijayshankersharma** [CodeHarborHub/codeharborhub.github.io#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add solution for 34. Find First and Last Position of Element in Sorted Array

### Use Case

I will provide proper description and comments.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@thevijayshankersharma Please limit the number of issues created per day to 4-5.
