### ISSUE TITLE
Add Layout in CSS

### ISSUE THREAD

**Issue by AmrutaJayanti** [CodeHarborHub/codeharborhub.github.io#540]
I would like to add layout in `CSS`. 

@Admin a small query, I have done some contributions in your repo in past few days. Those were merged into main and the issue was closed. But none of them are being counted in the leaderboard as leaderboard is updated. I raised an issue for the same and linked the PRs that were not counted. 

Could you also please look into the issue

**Comment by Yashgabani845** [comment]
@AmrutaJayanti you have more than 3 open issue please do not spam

**Comment by AmrutaJayanti** [comment]
@Yashgabani845 Its not any action of spam. I already have merged PRs from this repo. I just want to ask it considered my before and after update it dint include any of the PRs from this repo .

**Comment by AmrutaJayanti** [comment]
@Ajay-Dhangar Could you help me with this issue

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar Could you help me with this issue

Okay I will help @AmrutaJayanti

**Comment by AmrutaJayanti** [comment]
@Ajay-Dhangar Along with this there are other PRs too which are not counted

**Comment by Yashgabani845** [comment]
@AmrutaJayanti  i asked sanjay sir he told me that it is technical issue he will take care about it
