### ISSUE TITLE
[Feature Request]: to add Dijkstra algorithm documenatation 

### ISSUE THREAD

**Issue by Yashgabani845** [CodeHarborHub/codeharborhub.github.io#562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

in DSA section want to add dijkstra algorithm 
with intution,example,code,concept and conclusion section in this famous DSA algorithm 

### Use Case

adding docs

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Yashgabani845** [comment]
@Yashgabani845 completed my previous issues and made PR for them kindly assin this to me

**Comment by Yashgabani845** [comment]
@Ajay-Dhangar please look over my issues i have stated collect6ing info from resources please assign it so that  i can start work on this

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar please look over my issues i have stated collect6ing info from resources please assign it so that i can start work on this

okay,
