### ISSUE TITLE
[Feature Request]: Adding images to python documentation 

### ISSUE THREAD

**Issue by dhairyagothi** [CodeHarborHub/codeharborhub.github.io#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i can add some images to python documentation and documentation regarding getting started with python and how to install it

### Use Case

user will get more detailed documentation 

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/142989448/adeff0e3-0319-48d2-beed-28d9ebb44c79)

adding Gettiing Started in python documentation 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@
