### ISSUE TITLE
[Feature Request]:  Add Kadanes Algorithm's Documentation

### ISSUE THREAD

**Issue by Abhay182005dat** [CodeHarborHub/codeharborhub.github.io#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Greetings !!

Abhay here :) I would like to add Kadane's Algorithm Documentation for the website and also the code in 4 languages.
I hope this finds useful.

Thank You

### Use Case

Kadane's algorithm is used for optimizing the problem ,mainly for max subarray question

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Abhay182005dat** [comment]
Sir where should i add this Doc ?

**Comment by Ajay-Dhangar** [comment]
@Abhay182005dat Please complete your task otherwise I will close it.

**Comment by Abhay182005dat** [comment]
Yeah sir I will do it as soon as possible,I am having internals so ...
Pardon me

Thank you
