### ISSUE TITLE
[Leetcode]: Minimum Difference Between Largest and Smallest Value in Three Moves 

### ISSUE THREAD

**Issue by manishh12** [CodeHarborHub/codeharborhub.github.io#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add solution for above under leetcode-solution section.

### Use Case

I will provide proper description and comments.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Yashgabani845** [comment]
@manishh12 do not open more than 4 issue at a time
it's Spam

**Comment by manishh12** [comment]
@Yashgabani845 okay will take care from next time

**Comment by Ajay-Dhangar** [comment]
@manishh12  you cannot open a new issue today because you currently have four open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.
