### ISSUE TITLE
[Feature Request]: Next JS Icon 

### ISSUE THREAD

**Issue by Parth20GitHub** [CodeHarborHub/codeharborhub.github.io#592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add NEXT JS icon in the docs section is missing.

### Use Case

I will add it.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
- [ ] Go to site for icon: https://icons8.com/icons/set/nextjs

- [ ] select first icon and click on download 

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/99037494/72a02946-cbe2-4d95-80be-cc8f4e5d58f6)

- [ ] Choose SVG and select 48X48 then click on download and rename icon with `next-js.svg`

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/99037494/d038bdf1-0917-4da1-ac7e-a1e5e5ab67da)
