### ISSUE TITLE
Feature Engineering

### ISSUE THREAD

**Issue by AmrutaJayanti** [CodeHarborHub/codeharborhub.github.io#601]
I would like to add about Feature-Engineering in `python`

**Comment by Ajay-Dhangar** [comment]
@AmrutaJayanti can you provide more details.

**Comment by AmrutaJayanti** [comment]
@Ajay-Dhangar  `Feature-Engineering` includes feature extraction ,feature transformation , feature selection used in Machine Learning. I would like to add it in `python`
