### ISSUE TITLE
[Feature Request]: I want to add a scientific calculator site made in HTML, CSS and Vanilla Javascript under the showcase section. I want to contribute under GSSOC'24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [CodeHarborHub/codeharborhub.github.io#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I went through the showcase section of the website and found no projects under HTML CSS section. So,  I want to add a scientific calculator project made in HTML, CSS and Javascript under that section. Here is a snapshot of the project : 

![Screenshot 2024-06-06 155021](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/123104247/78ca49dd-2a14-4be2-97ff-72038a48ad78)

### Use Case

I think that this addition would be highly helpful as the showcase section would have another project to be added under it. My project is completely self coded and beginner friendly under HTML and CSS section. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
Now you can add in here same format https://github.com/CodeHarborHub/codeharborhub.github.io/blob/d000cd7f314e0bc321f9f02353697407592e01aa/src/data/users.tsx#L221 and also add image.
