### ISSUE TITLE
[Feature Request]: I would like to add solution for 100. Same Tree

### ISSUE THREAD

**Issue by thevijayshankersharma** [CodeHarborHub/codeharborhub.github.io#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add solution for 100. Same Tree

### Use Case

I will provide proper description and comments.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , i have already added solution of that problem you can close this issue.

**Comment by thevijayshankersharma** [comment]
@Ajay-Dhangar So should I raise for 8 issue cause you haven't assigned none of them I raised yesterday.

**Comment by thevijayshankersharma** [comment]
@Ajay-Dhangar is this looking like this or only for me?

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/109781385/8717a677-4883-4b14-9828-59071fc1a3f6)

**Comment by Vipullakum007** [comment]
hey @thevijayshankersharma , its looks like this don't see preview always.
![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/03d3a4b0-02f4-4e88-a58a-165a4b3042f2)

**Comment by thevijayshankersharma** [comment]
@Vipullakum007 Never mind. I was just asking.

**Comment by Ajay-Dhangar** [comment]
can you explain or share more details about it
