### ISSUE TITLE
[Feature Request]: I would like to add solution for 108. Convert Sorted Array to Binary Sear...

### ISSUE THREAD

**Issue by thevijayshankersharma** [CodeHarborHub/codeharborhub.github.io#620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add solution for 108. Convert Sorted Array to Binary Sear...

### Use Case

I will provide proper description and comments.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@thevijayshankersharma you cannot open a new issue today because you currently have four (4) open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.

**Comment by thevijayshankersharma** [comment]
@Ajay-Dhangar this is not a duplicate one check it out the repo.
