### ISSUE TITLE
[Feature Request]: I would like to add solution for 110. Balanced Binary Tree

### ISSUE THREAD

**Issue by thevijayshankersharma** [CodeHarborHub/codeharborhub.github.io#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add solution for 110. Balanced Binary Tree

### Use Case

I will provide proper description and comments.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@thevijayshankersharma you cannot open a new issue today because you currently have four (4) open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.

**Comment by thevijayshankersharma** [comment]
> @thevijayshankersharma you cannot open a new issue today because you currently have four (4) open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.

Yeah I know that's why I didn't raised any more than what you told me.

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , i have already added solution of that problem you can close this issue. you can check it here
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/508

**Comment by Ajay-Dhangar** [comment]
@thevijayshankersharma Please checkout contents, issues, and prs before create new issue.
