### ISSUE TITLE
[Feature Request]:  Add Graph Algorithms

### ISSUE THREAD

**Issue by MuraliDharan7** [CodeHarborHub/codeharborhub.github.io#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To add Graph Algorithms in GFG Documentation:

1. Dijkstra's Algorithm: Finds the shortest path between nodes in a graph with non-negative edge weights.
2. Bellman-Ford Algorithm: Computes shortest paths from a single source node to all other nodes, even with negative weights.
3. Floyd-Warshall Algorithm: Finds shortest paths between all pairs of nodes.
4. Kruskal’s and Prim’s Algorithms: Used for finding the minimum spanning tree in a graph.

### Use Case

Widely used in Solving GRAPH Hard problems.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@MuraliDharan7 you cannot open a new issue today because you currently have four (4) open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.
