### ISSUE TITLE
[Feature Request]: Time Complexity in Details

### ISSUE THREAD

**Issue by MuraliDharan7** [CodeHarborHub/codeharborhub.github.io#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- I want to add the article about Time Complexity.
- This is going to explain all the topics in TC and also it would have images for good understanding and the resources, problems as well.

### Use Case

TC is the one which need to be understood by all the programmers who code with problem solving.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@MuraliDharan7 you cannot open a new issue today because you currently have four (4) open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.
