### ISSUE TITLE
[Python Docs]: Python networking section add

### ISSUE THREAD

**Issue by Vipullakum007** [CodeHarborHub/codeharborhub.github.io#636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add Python Networking section .

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/158b1675-5924-430d-8aa1-16fb1619e92e)

### Use Case

use know more about networking in python.

### Benefits

use know more about networking in python.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar  , please look over my issues i have stated collecting info from resources please assign it so that i can start work on this

**Comment by Ajay-Dhangar** [comment]
@Vipullakum007 you cannot open a new issue today because you currently have four (4) open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.

**Comment by Ajay-Dhangar** [comment]
@Vipullakum007 you cannot open a new issue today because you currently have four (4) open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.
