### ISSUE TITLE
[Leetcode]: i want to add solution of leetcode problem 213 . House Robber II

### ISSUE THREAD

**Issue by Vipullakum007** [CodeHarborHub/codeharborhub.github.io#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 i want to add solution of leetcode problem 213 . House Robber II

### Use Case

user can see solution if he trys a lot but don't get solution or know more about another solution.

### Benefits

user can see solution if he trys a lot but don't get solution or know more about another solution.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar  ,please assign issue to me. i have already solution of it

**Comment by Ajay-Dhangar** [comment]
@Vipullakum007 you cannot open a new issue today because you currently have four (4) open issues. Please ensure a clean and organized environment and avoid creating spam. This project is part of GSSoc'24, which has strict rules, so it is important to follow all instructions.

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , can close this 2 issue because another have already add solution. so that i can raise new issue
https://github.com/CodeHarborHub/codeharborhub.github.io/issues/420
https://github.com/CodeHarborHub/codeharborhub.github.io/issues/406

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar   , after closing that 2 issue can you please assign this issue to me

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , many person raise issue that solution already exist please check it many then i have found more you can.
https://github.com/CodeHarborHub/codeharborhub.github.io/issues/619
https://github.com/CodeHarborHub/codeharborhub.github.io/issues/617
#616 
https://github.com/CodeHarborHub/codeharborhub.github.io/issues/621

**Comment by Vipullakum007** [comment]
> hey @Ajay-Dhangar , many person raise issue that solution already exist please check it many then i have found more you can. #619 #617 #616 #621

you can directly close them

**Comment by Ajay-Dhangar** [comment]
@Vipullakum007, thanks for informing me. The issue titles are different, so I couldn't view the full details. Thanks again, and I appreciate your contributions. You're doing your best!
