### ISSUE TITLE
Leetcode Problem [ 104 - 107 ]

### ISSUE THREAD

**Issue by Sid-80** [CodeHarborHub/codeharborhub.github.io#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am willing to add the solution of following leetcode problems :
Problem Number : 104,105, 106, 107.

### Use Case

This is for the DSA problems

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Sid-80 Please complete your task otherwise I will close it.
