### ISSUE TITLE
[Feature Request]: Add solution for LT problem 119 . Pascal's Triangle II

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [CodeHarborHub/codeharborhub.github.io#670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add a solution for [. Pascal's Triangle II](https://leetcode.com/problems/pascals-triangle-ii)

### Use Case

it will help the users to get the solution for the Leetcode problem 119

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Ayushmaanagarwal1211 Please open only 4 issues everyday not opening large otherwise I can't assign to you.

**Comment by Ayushmaanagarwal1211** [comment]
Ok sure actually i am new to this repo i will keep in mind for future  issues
