### ISSUE TITLE
[Feature Request]: Responsive Design Tutorial

### ISSUE THREAD

**Issue by Yashgabani845** [CodeHarborHub/codeharborhub.github.io#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

in CSS section
i want to add docs for responsive design which will have deep description about media queries and aspects of responsive design

### Use Case

docs for css

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Yashgabani845 Please complete your task otherwise I will close it.

**Comment by Yashgabani845** [comment]
@Ajay-Dhangar sorry sir 
There was one accident in our family 
Still I'll try to complete it tomorrow itself

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar sorry sir There was one accident in our family Still I'll try to complete it tomorrow itself

@Yashgabani845 Okay, take your time. You can complete the task whenever it's possible for you. Take care.

**Comment by Yashgabani845** [comment]
i will not able to complete it in few days 
so i am closing it
