### ISSUE TITLE
add leetcode solution of 126 and 127

### ISSUE THREAD

**Issue by mahek0620** [CodeHarborHub/codeharborhub.github.io#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

solutions for word ladder and word ladder 2

### Suggested Change

.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by mahek0620** [comment]
@Ajay-Dhangar as this issue contains both hard question , can you please update the labels considering it

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar as this issue contains both hard question , can you please update the labels considering it

I will update based on your content.
