### ISSUE TITLE
[Bug]: position of x and instagram.

### ISSUE THREAD

**Issue by dnyandeepchute** [CodeHarborHub/codeharborhub.github.io#688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

position of x and instagram are not looking good.

### Expected behavior

interchange the position

### Add ScreenShots

![Screenshot 2024-06-07 125351](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/158272735/8af36531-e5d3-4b8f-8312-75df0f570e7e)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by hardiksharma02** [comment]
@dnyandeepchute  where will you keep the position send the screenshot

**Comment by dnyandeepchute** [comment]
@hardiksharma02 already mentioned in Expected behavior that i will interchange the position as it looks good.

**Comment by dnyandeepchute** [comment]
@hardiksharma02 instagram is not present there i will add it and fix the position, please increase it to level2, thank you

**Comment by Ajay-Dhangar** [comment]
Hi @dnyandeepchute, we've made some changes to our code, so please make sure to incorporate the latest updates from the main branch into your own. We've decided to remove the Instagram functionality as it's not essential for our project. This change isn't related to any specific issue, so feel free to close it and focus on other tasks. Apologies for any inconvenience, and thank you for your time.

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/99037494/5bfdbb30-1af0-4107-97c4-6f912f8f6bf1)
