### ISSUE TITLE
[Feature Request]: adding github

### ISSUE THREAD

**Issue by dnyandeepchute** [CodeHarborHub/codeharborhub.github.io#689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding github in footer

### Use Case

contact

### Benefits

contact improvement.

### Add ScreenShots

![Screenshot 2024-06-07 125351](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/158272735/a8f5b219-8a26-4bf9-a6ad-0d8195ecbfea)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by hardiksharma02** [comment]
github is already added in quick link no need @dnyandeepchute
