### ISSUE TITLE
[Feature Request]:  To add recommended courses

### ISSUE THREAD

**Issue by patelkiran185** [CodeHarborHub/codeharborhub.github.io#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add recommended courses for languages like Node,MongoDb,etc

### Use Case

No need to search online,easy navigation to learn the course

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by patelkiran185** [comment]
@Ajay-Dhangar assign this to me

**Comment by hardiksharma02** [comment]
@patelkiran185 we may assign you this issue but tell us the approach what all will you add

**Comment by patelkiran185** [comment]
> @patelkiran185 we may assign you this issue but tell us the approach what all will you add

![Screenshot from 2024-06-07 21-36-54](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/138752385/70d79843-a74d-4922-b29a-2d3e14c2bab6)
The search bar on the page does not appear to be working for Figma,mongodb,Node and many other courses.The alogorithm used behind either does not have those courses or is not able to find the keyword. So i would like to add few.
