### ISSUE TITLE
Add Guess The Number Game in the Showcase Section. I want to contribute under GSSOC'24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [CodeHarborHub/codeharborhub.github.io#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I have built a Guess The Number Game in HTML, CSS and Javascript. 

Features : 1. Background Music option is provided.
2. The user can choose easy, medium or hard levels according to the choice.

### Use Case

This will add a project under the Showcase section.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by hardiksharma02** [comment]
@ParnaRoyChowdhury777 can you share some screenshot or rough design of the number game

**Comment by ParnaRoyChowdhury777** [comment]
> @ParnaRoyChowdhury777 can you share some screenshot or rough design of the number game

sure Sir,  here it is 

![Screenshot 2024-06-07 210550](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/123104247/a52c6e12-1d82-4667-9dc8-b8b5ace987d1)
