### ISSUE TITLE
[Feature Request]: Resume Builder WebApp Project (CRUD)

### ISSUE THREAD

**Issue by Sambit-Mondal** [CodeHarborHub/codeharborhub.github.io#705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Nowadays, everyone, ranging from a student to a working professional, needs a well-built resume to apply to companies for jobs and internships. A resume not only reflects their skills but also reflects their personality and character. Companies believe much on first impression, and a good resume is what impresses them. But, the applicants either become unsuccesful to create a good resume or it takes a lot of time finding a good template for resume, and edit it.

### Use Case

- The Resume Builder would make the resume building process a cakewalk!
- Just enter the details like, name, personal details, academic details, work experience, skills, etc and boom, the resume will be ready in just a click!
- Also, the user will be able to update the details dynamically, including adding or removing sections, update personal information, or update new skills that they've learnt.
- More interestingly, the users will also be able to download their generated resume as PDF.

### Benefits

The Resume Builder extension will allow users to create their own resume in a hassle-free way, download the resume as pdf and also update their skills or personal details later, as per requirements. The feature will be completed when users will be able to enter their details, add or remove sections, update the details dynamically, and also generate and download a pdf of their resume.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Sambit-Mondal Please complete your task otherwise I will close it.

**Comment by Sambit-Mondal** [comment]
@Ajay-Dhangar Sir, I'm unable to understand what is happening. I've pulled the changes, but there's some issue. Kindly help me with how to fix this:

![Screenshot 2024-06-09 215807](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/138088550/cfe292c5-1a81-4327-8226-21422a1cd6fd)

**Comment by Ajay-Dhangar** [comment]
I will solve it So, can you send PRs and reference of this issue I resolve it for you
