### ISSUE TITLE
[Feature Request]: Adding LC solution for 1544. Make The String Great

### ISSUE THREAD

**Issue by aaradhyasinghgaur** [CodeHarborHub/codeharborhub.github.io#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Useful for user to be able to solve complex/hard problems similar to this whenever somebody want a solution for this.

### Use Case

For users to be able to see the solutions and understand different approaches for it.

### Benefits

The use case is a benefit.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by kyra-09** [comment]
@Ajay-Dhangar kindly assign issues opened by me .
