### ISSUE TITLE
[Documentation Update]: Adding KnapSack Problem

### ISSUE THREAD

**Issue by Parth20GitHub** [CodeHarborHub/codeharborhub.github.io#716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

In DSA section, adding new algorithm namely Knapsack Problem

### Suggested Change

dsa part will be changed

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MuraliDharan7** [comment]
Already Added Check #627

**Comment by Parth20GitHub** [comment]
> Already Added Check #627

Updated My Issue
