### ISSUE TITLE
[Feature Request]: add Ebooks section 

### ISSUE THREAD

**Issue by mukilan2815** [CodeHarborHub/codeharborhub.github.io#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We can add Ebooks section in this website using free books api. So that users can easily get accessed to Ebooks.

Assign this under GSSOC'24. I think this comes under level 3. 

### Use Case

Instead of searching for books , we can provide free books in this website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by hardiksharma02** [comment]
@mukilan2815 can you elaborate more on your approach and where will you add the e book section

**Comment by mukilan2815** [comment]
![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/71129858/bbd06c47-957e-4876-ab8d-568b2059b26f)

in the navbar Ebooks option will be there. 

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/71129858/3d88e2c8-e337-4460-babb-8f4bb41f6a99)

Sample ui taken form google for reference.

**Comment by hardiksharma02** [comment]
@mukilan2815 ok try and go ahead with this i am assigning this to you

**Comment by Ajay-Dhangar** [comment]
@mukilan2815 Please complete your task otherwise I will close it.

**Comment by mukilan2815** [comment]
I'm working on this i will finish it soon
