### ISSUE TITLE
Add Solution of LeetCode problem 206

### ISSUE THREAD

**Issue by Saksham2k3s** [CodeHarborHub/codeharborhub.github.io#720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It will provide the optimized solution for the problem 206

### Use Case

It will provide the optimized solution for the problem 206

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Saksham2k3s complete task otherwise I will close it.
