### ISSUE TITLE
Algorithm section: improve the code reading section 

### ISSUE THREAD

**Issue by W-ight** [CodeHarborHub/codeharborhub.github.io#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

In <br />
* Dijkstra's
* Hashing
* Prim's Algorithm
* Linear Search and Binary Search Algorithms
The code part does not have Line number, java code is not in right color format and one by one implementation code for java, cpp, python, javascript.

### Suggested Change

* Add Line Numbers.
* Add color format in java code.
*  Adddtab for java, cpp and javascript code to switch between programming language makes the tutorial more readable.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

@Ajay-Dhangar I want to work on this.

**Comment by Ajay-Dhangar** [comment]
@W-ight Sure, and you will need to use https://docusaurus.io/ as our project relies on its functionality.
