### ISSUE TITLE
Adding CSS BACKGROUND in documentation

### ISSUE THREAD

**Issue by Parth20GitHub** [CodeHarborHub/codeharborhub.github.io#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is lack of css background in docs section

### Use Case

I would add the background section.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@Parth20GitHub complete task otherwise I will close it.
