### ISSUE TITLE
[Feature Request]:  Adding Spotify Clone Project

### ISSUE THREAD

**Issue by SadafKausar2025** [CodeHarborHub/codeharborhub.github.io#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I have made spotify clone with the help of HTML , CSS AND JS
I want to add this Project here

### Use Case

.

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/137484958/d55a403d-0617-4cdc-94bc-6ba7a737bdab)

![Screenshot (1961)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/137484958/2032ede4-79fc-41e7-a4db-15f4042f6ce2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SadafKausar2025** [comment]
hello @Ajay-Dhangar 
can you please assign me this issue?

**Comment by SadafKausar2025** [comment]
hello @Ajay-Dhangar 
It's Not documentation, It's a big project.

**Comment by SadafKausar2025** [comment]
hello @Ajay-Dhangar 
can you please help me in finding showcase page
I am not getting please help me

**Comment by Ajay-Dhangar** [comment]
> hello @Ajay-Dhangar can you please help me in finding showcase page I am not getting please help me

okay

### Links

Your source code: https://github.com/CodeHarborHub/codeharborhub.github.io/blob/main/src/data/userData.tsx
Image add in: https://github.com/CodeHarborHub/codeharborhub.github.io/tree/main/src/data/showcase

## Guide

Site title: <= 60 characters
Site description: ≤120 characters
Site URL: live URL of your site
Site source code URL: your site source code
Tags: see below the list of available tags 
https://github.com/CodeHarborHub/codeharborhub.github.io/blob/790394b42c35e42896702df704c6a6c8ec24d8c4/src/data/users.tsx#L9

**Comment by Ajay-Dhangar** [comment]
> hello @Ajay-Dhangar It's Not documentation, It's a big project.

I know but this is my mistake click on document label 🔖
