### ISSUE TITLE
[Feature Request]: Add 100 easy question gfg

### ISSUE THREAD

**Issue by agastya3636** [CodeHarborHub/codeharborhub.github.io#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add 100 easy question gfg

### Use Case

Practice question of dsa

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@agastya3636 complete task otherwise I will close it.
