### ISSUE TITLE
[Feature Request]: Addition of 100 medium questions of geeksforgeeks

### ISSUE THREAD

**Issue by agastya3636** [CodeHarborHub/codeharborhub.github.io#808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 Addition of 100 medium questions

### Use Case

Practice question for dsa

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@agastya3636 complete task otherwise I will close it.

**Comment by agastya3636** [comment]
Ok I will complete by today
