### ISSUE TITLE
[Feature Request]: Addition of all school level problem from gfg

### ISSUE THREAD

**Issue by agastya3636** [CodeHarborHub/codeharborhub.github.io#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of all school level problem from gfg

### Use Case

Practice question for beginners

### Add ScreenShots

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/124435030/45215ad8-2ae8-48e2-b488-5c80a6ea4312)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@agastya3636 complete task otherwise I will close it.
