### ISSUE TITLE
[Feature Request]: Add Content: DP algorithms LCS, LIS and FIbonacci Sequence

### ISSUE THREAD

**Issue by kosuri-indu** [CodeHarborHub/codeharborhub.github.io#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to create a Dynamic Programming Folder, where I will store the current DP algorithms available in the repo and also add three new DP algorithms:
- Longest Common Subsequence (LCS)
- Longest Increasing Subsequence (LIS)
- Fibonacci Sequence Algorithm

### Use Case

To understand DP algorithms

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by kosuri-indu** [comment]
@Ajay-Dhangar 
Please assign this issue to me under `level3`.
As I will be adding 3 new Dynamic Programming Algorithms.
Thank you

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar Please assign this issue to me under `level3`. As I will be adding 3 new Dynamic Programming Algorithms. Thank you

@kosuri-indu  Focus on quality over quantity. If your content is well-explained, high-quality, and follows our structure, I will promote you to Level 3 to encourage you.

**Comment by kosuri-indu** [comment]
> > @Ajay-Dhangar Please assign this issue to me under `level3`. As I will be adding 3 new Dynamic Programming Algorithms. Thank you
> 
> @kosuri-indu Focus on quality over quantity. If your content is well-explained, high-quality, and follows our structure, I will promote you to Level 3 to encourage you.
> 
> and level2 is default level for docs but If write your good content then I will update on both (in issues and PRs).

Sure. Thank you for considering!
