### ISSUE TITLE
[Feature Request]: Hover and tilt effect.

### ISSUE THREAD

**Issue by happyrao78** [CodeHarborHub/codeharborhub.github.io#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add the hover and tilt effect to cards present in showcase section as currently they are static even when hovered which is not a good practice.

### Use Case

I would like to use the javascript and css for implementing my proposed feature.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@happyrao78  Please focus solely on CSS to showcase the component. Avoid other effects, as we have extensive files, folders, and components. For maintainability, it's essential to use best practices, such as applying full paths to selectors (e.g., parent, child, sub-child). This will help ensure our code remains organized and maintainable.
