### ISSUE TITLE
[Feature Request]: Add the respective icons in the footer

### ISSUE THREAD

**Issue by namandude** [CodeHarborHub/codeharborhub.github.io#829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Respective apps icons in the footer in  github insta X facebook

### Use Case

I make looks good and give the unique identity to classify just by looking

### Add ScreenShots

![Screenshot 2024-06-09 124914](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/118013565/531e0c97-8f09-4e57-8306-0ce12e13e67a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
But we don't want to use insta, and  facebook.

**Comment by namandude** [comment]
@Ajay-Dhangar  Ok i am adding  only mentioned there .'
Thank You!!

**Comment by Ajay-Dhangar** [comment]
@namandude Please complete your task otherwise I will close it.

**Comment by namandude** [comment]
@Ajay-Dhangar  Yes i am adding it sorry for the delay
