### ISSUE TITLE
The website doesn't contain login page

### ISSUE THREAD

**Issue by Its-your-rj** [CodeHarborHub/codeharborhub.github.io#836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When I was going through a website i saw that the website doesn't contain Login page please assign me a task to make login page for website.

### Use Case

1) User Authentication
2)Session Management
3)Password Recovery

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Its-your-rj** [comment]
@Ajay-Dhangar please assign me this issue under GSSOC'24 with level 3 label this will help me a lot in order to learn and contribute.

**Comment by Ajay-Dhangar** [comment]
@Its-your-rj , I recognize the importance of implementing back-end or login functionality, but given the current situation, it's not viable for us to proceed with it right away. We've encountered some challenges with our existing domain, particularly with handling large volumes of requests from open-source contributors. Therefore, I suggest we hold off on this for now and revisit it at a later time. In the meantime, feel free to create new issues, and I'll ensure they are addressed accordingly.
