### ISSUE TITLE
[Feature Request]: Cses problem section

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [CodeHarborHub/codeharborhub.github.io#837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

we have many options for leetcode but nowdays we cannot find solution of cses so i suggest we should add section of cses problem and i can contribute solutions of some question of section tree graph dynammic programming etc

### Use Case

it helps useful to solve cses problem which is very important

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@agarwalhimanshugaya Please complete your task otherwise I will close it.
