### ISSUE TITLE
[Documentation Update]: Add LeetCode Solution for Problem 107(Binary Tree Level Order Traversal II)

### ISSUE THREAD

**Issue by Harleen-786** [CodeHarborHub/codeharborhub.github.io#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I would like to add a solution for the LeetCode problem "Binary Tree Level Order Traversal II" (Problem 107) to the project. This problem involves performing a level order traversal on a binary tree but returning the node values in reverse level order.

### Suggested Change

I suggest adding a comprehensive solution to the Binary Tree Level Order Traversal II problem in multiple programming languages, including C++, Python, Java, and JavaScript. This solution will include:

1. Clear and well-documented code.
2. An explanation of the algorithm and its complexity.
3. Example test cases to demonstrate the correctness of the solution.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Harleen-786** [comment]
@Ajay-Dhangar please assign the issue

**Comment by Ajay-Dhangar** [comment]
@Harleen-786 Please complete your task otherwise I will close it.
