### ISSUE TITLE
add functionality to contact form

### ISSUE THREAD

**Issue by ananyag309** [CodeHarborHub/codeharborhub.github.io#893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Currently contact form is not accepting responses

### Suggested Change

will add functionality to it, it will accept response, display confirmation message and reset the form for better practice

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@ananyag309 I also used `console.log` to display data in the console, but you can apply more advanced logic and functionality as needed.

**Comment by Ajay-Dhangar** [comment]
@ananyag309 Please complete your task otherwise I will close it.
