### ISSUE TITLE
[Documentation Update]: Adding String topic After Binary Search topic in DSA

### ISSUE THREAD

**Issue by SadafKausar2025** [CodeHarborHub/codeharborhub.github.io#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

.

### Suggested Change

![Screenshot (1968)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/137484958/40f0a9d0-7e7a-48a0-bcc7-50fb4f2b8f0f)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@SadafKausar2025 You need to sync or pull or may be used our latest main branch for our latest code

**Comment by SadafKausar2025** [comment]
hello @Ajay-Dhangar 
you have not given level in my binary search PR
Please give it

**Comment by SadafKausar2025** [comment]
yes I will sync and do git pull to update
