### ISSUE TITLE
Object Oriented Programming tutorials

### ISSUE THREAD

**Issue by PrathicaShettyM** [CodeHarborHub/codeharborhub.github.io#93]
@Ajay-Dhangar I would like to add OOPs concepts also so that People who visit the website will be able gain knowledge on Object Oriented Concepts also which will help them for placements and all. Can you please assign me this task?

**Comment by Ajay-Dhangar** [comment]
yah sure, but followed our structure for example [codes](https://github.com/CodeHarborHub/codeharborhub/blob/main/docs/javascript) and [preview](https://www.codeharborhub.live/docs/category/javascript).

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Comment by PrathicaShettyM** [comment]
Yes sir

**Comment by Ajay-Dhangar** [comment]
**I suggest you work and make or covered all topics like:**

```md
📁 Object-Oriented Programming Tutorials
|
├── 📁 01_Introduction_to_OOP
|   ├── 📄 01_What_is_OOP.md
|   ├── 📄 02_Principles_of_OOP.md
|   ├── 📄 03_Benefits_of_OOP.md
|   └── ...
|
├── 📁 02_Classes_and_Objects
|   ├── 📄 01_Defining_Classes.md
|   ├── 📄 02_Creating_Objects.md
|   ├── 📄 03_Class_Constructors.md
|   └── ...
|
├── 📁 03_Inheritance
|   ├── 📄 01_Inheriting_Properties_and_Methods.md
|   ├── 📄 02_Overriding_Methods.md
|   ├── 📄 03_Multiple_Inheritance_and_Interface.md
|   └── ...
|
├── 📁 04_Encapsulation
|   ├── 📄 01_Getters_and_Setters.md
|   ├── 📄 02_Access_Modifiers.md
|   ├── 📄 03_Encapsulation_in_Practice.md
|   └── ...
|
├── 📁 05_Polymorphism
|   ├── 📄 01_Method_Overloading.md
|   ├── 📄 02_Method_Overriding.md
|   ├── 📄 03_Runtime_Polymorphism.md
|   └── ...
|
├── 📁 06_Abstract_Classes_and_Interfaces
|   ├── 📄 01_Abstract_Classes.md
|   ├── 📄 02_Interface_Basics.md
|   ├── 📄 03_Implementing_Interfaces.md
|   └── ...
|
├── 📁 07_Composition_and_Aggregation
|   ├── 📄 01_Composition_vs_Aggregation.md
|   ├── 📄 02_Using_Composition.md
|   ├── 📄 03_Using_Aggregation.md
|   └── ...
|
├── 📁 08_Design_Principles_and_Patterns
|   ├── 📄 01_SOLID_Principles.md
|   ├── 📄 02_Design_Patterns_Overview.md
|   ├── 📄 03_Creational_Design_Patterns.md
|   └── ...
|
└── 📁 09_Advanced_Topics_and_Applications
    ├── 📄 01_Generic_Programming.md
    ├── 📄 02_Refactoring_and_Code_Smells.md
    ├── 📄 03_Object-Oriented_Design_Principles_in_Practice.md
    └── ...
```

**Comment by Chanc2206** [comment]
hey i have hackerrank with 5 stars ,i think im best suited for the role kindly assign me!!

**Comment by iamanolive** [comment]
@Ajay-Dhangar can i work on this?

**Comment by Ajay-Dhangar** [comment]
@PrathicaShettyM , @Chanc2206 , @iamanolive can anyone complete this issue otherwise I close it.
