### ISSUE TITLE
[Feature Request]: i want to add solutions of problem no 312-burst ballons

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [CodeHarborHub/codeharborhub.github.io#930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It is the hard problem and nice dp problem which teachs a nice idea of solving dp with removal of element i want to upload this solution because it is a good and hard question

### Use Case

it teaches a hard and good knowledge of dp 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@agarwalhimanshugaya Please complete your task otherwise I will close it.
