### ISSUE TITLE
[Feature Request]: add important kosaraju algorithm in graph 

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [CodeHarborHub/codeharborhub.github.io#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i see in graph there is one important algorithm is missing i want to add that algorithm that name is kosaraju algorithm . This algorithm uses in competitive programming and also in dsa

### Use Case

in solving hard question of graph

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@agarwalhimanshugaya Please complete your task otherwise I will close it.

**Comment by agarwalhimanshugaya** [comment]
i add it today night
