### ISSUE TITLE
Add LeetCode Solution(41)

### ISSUE THREAD

**Issue by VaishnaviMankala19** [CodeHarborHub/codeharborhub.github.io#971]
As a GSSoC24 contributor, I want to add a solution for LeetCode problem Number 41

**Comment by Ajay-Dhangar** [comment]
@VaishnaviMankala19 Please complete your task otherwise I will close it.

**Comment by VaishnaviMankala19** [comment]
@Ajay-Dhangar  This is Hard Problem leetcode(41) with acceptance rate 39.6% . Can I get level2 for it.
