### ISSUE TITLE
[MongoDB Docs] : Add Advanced MongoDB Docs 

### ISSUE THREAD

**Issue by Vipullakum007** [CodeHarborHub/codeharborhub.github.io#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add following Advanced MongoDB Docs 

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/1a5a69c4-9dd3-4ab5-9d87-6ad9e273fa1a)

### Use Case

User can know more about the advanced topic about MongoDB

### Benefits

User can know more about the advanced topic about MongoDB

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , please assign me i want to work on it.

**Comment by Ajay-Dhangar** [comment]
@Vipullakum007 Please complete your task otherwise I will close it.

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , i will complete it today.
