### ISSUE TITLE
[Feature Request]: To Add Solution of LC problem 75. Sort Colors

### ISSUE THREAD

**Issue by aryan-1309** [CodeHarborHub/codeharborhub.github.io#997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This problem is a Dutch National flag algorithm based problem. pls Assign this to me so that in can add this problem sol with Various technique in diff languages.

### Use Case

Nothing to preview

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment]
@aryan-1309 Please complete your task otherwise I will close it.

**Comment by Ajay-Dhangar** [comment]
@aryan-1309 please complete your task otherwise i will close it

**Comment by aryan-1309** [comment]
> @aryan-1309 please complete your task otherwise i will close it

It's already completed sir and PR has been accepted by you. You can close this issue.
